### ISSUE TITLE
wrong scaling size param

### ISSUE THREAD

**Issue by Vodolazz** [tomaszzmuda/Xabe.FFMpeg#1]
Hi, I came across the scale problem in your solution, it seems that scale factor is given to the command line inproperly, in one integer, while ffmpeg accepts %width%x%height% format, or preset alias.
More Info here:
https://ffmpeg.org/ffmpeg-utils.html#Video-size

I fixed the problem, so if you accept contributors to your project, please create branch and I'll push the fix.

**Comment by tomaszzmuda** [comment]
Hi.
Thank you for reporting problem. I've created branch develop - I hope i set right permissions to it.
Tell me if you can push there, or create fork and make pull request to this repository.

**Comment by tomaszzmuda** [comment]
I have done it in new version. Please update package to version 1.4.0.
