### ISSUE TITLE
Option to force exit FFmpeg

### ISSUE THREAD

**Issue by Szelzz** [tomaszzmuda/Xabe.FFmpeg#106]
When you try to open non existing stream from FFmpeg it will freeze until you press ctrl+z. 
Wrapper works by passing q to StandardInput so CancellationToken doesn't work.

Steps to reproduce:
1. Create `Conversion` with input `rtsp://192.168.1.123:554/` (this ip address points to nothing).
2. Start and try to cancel with CancellationToken.

Maybe automatically terminate process when it not finishes for 2 sec after cancelling?

**Comment by tomaszzmuda** [comment]
I don't know 2 seconds will be enough.
I'll take a look later.

**Comment by tomaszzmuda** [comment]
I am sorry to have kept you waiting for so long.
After investigate this issue I will take too much work to do it now.
I'll try to do in in next release.
