### ISSUE TITLE
Better subtitle support

### ISSUE THREAD

**Issue by alex6dj** [tomaszzmuda/Xabe.FFmpeg#108]
For burning subtitles you only accept an string with a .srt file as input. This work for an external file but if you want  to use a subtitle included inside the video file, you can´t use this otion.

For example, to render the file sub.srt on top of the input video, you use the command: 
`subtitles=sub.srt`
To render the default subtitles stream from file video.mkv, use: 
`subtitles=video.mkv`
To render the second subtitles stream from that file, use: 
`subtitles=video.mkv:si=1`

With the same idea but in the input using a SubtitleStream you can implement this option an allow to render an .srt, .ass and a subtitle right from the video file. You should check the kind of input subtitle just in case it isn´t allowed.

**Comment by alex6dj** [comment]
Another thing, I see you are using a Dictionary for _videoFilters on VideoStream it can be problematic when you want to burn 2 subtitles. Why do that?, well usually you have inside the video file a subtitle with all the dialogs and another with the translations of signs. :)

**Comment by tomaszzmuda** [comment]
Thanks for advice.
This will be added in (probably) next version.
