### ISSUE TITLE
Why is AsyncHelper internal?

### ISSUE THREAD

**Issue by ruant** [tomaszzmuda/Xabe.FFmpeg#118]
Hi.
Messing around with creating some custom `Conversion.Helpers`
(Combining the Concatenate and Audio so it's done in one process)

But when just copying the code and merging them into one, I stumbled into AsyncHelper not being available due to it's being internal.

Workaround would be to just copy it...

**Comment by tomaszzmuda** [comment]
@ruant used custom arguments and that works.
I think about it a lot but AsyncHelper is only a little "hack" to Conversion.Helpers method always returns IConversion.
Without it building conversion would like this:
`await (await Conversion.ToMp4("", "")).UseMultiThread(true).Start()`
We have got issues with running this with Task.Result, Task.Wait() or Task.RunSynchronously() so we implemented something what shoudn't make any trouble. But I strongly discourage from using this.
