### ISSUE TITLE
Concatenate multiple h264 files in a folder then convert to mp4

### ISSUE THREAD

**Issue by younganakin** [tomaszzmuda/Xabe.FFmpeg#12]
How do you concatenate multiple files in a folder?
Equivalent to this in ffmpeg command line but without the mylist.txt
ffmpeg -f concat -i mylist.txt -c copy output.mp4

**Comment by tomaszzmuda** [comment]
Hi.
In ConversionHelper.cs is a method:
```
        /// <summary>
        ///     Concat multiple inputVideos
        /// </summary>
        /// <param name="output">Concatenated inputVideos</param>
        /// <param name="inputVideos">Videos to add</param>
        /// <returns>Conversion result</returns>
        [UsedImplicitly]
        public static async Task<bool> JoinWith(string output, params string[] inputVideos)
```
or you can use Concat(params string[] paths) in Conversion class.
Example:
```
await new Conversion().
                Concat(pathList.ToArray())
                                         .StreamCopy(Channel.Both)
                                         .SetBitstreamFilter(Channel.Audio, Filter.Aac_AdtstoAsc)
                                         .SetOutput(output)
                                         .Start();
```

I hope this what are you looking for. If not please tell me more about effect you want to get, I'll implement this.

**Comment by younganakin** [comment]
Thanks for your help......it works....

**Comment by jawadatgithub** [comment]
The current Concat implementation is limited:
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/master/Xabe.FFmpeg/Conversion.cs#L422

as it follow https://trac.ffmpeg.org/wiki/Concatenate#protocol
`ffmpeg -i "concat:input1.mpg|input2.mpg|input3.mpg" -c copy output.mpg`

Implementing `ffmpeg -f concat -i mylist.txt -c copy output.mp4` **requires** https://trac.ffmpeg.org/wiki/Concatenate#demuxer

**Comment by tomaszzmuda** [comment]
@jawadatgithub 
Thank you for note that.
I'll implement it in few days.

**Comment by tomaszzmuda** [comment]
I have changed implementation of concatenate videos.
Now it's using demuxer.
