### ISSUE TITLE
Tests for M3U8Stream

### ISSUE THREAD

**Issue by tomaszzmuda** [tomaszzmuda/Xabe.FFmpeg#13]
Method SaveM3U8Stream in ConversionHelper is untested.
I don't have any idea how to test it.
Theoretically it should works, but it has to be tested soon.

**Comment by davweiss** [comment]
ConversionHelper:257 need to change from 
`if(uri.Scheme != "http" ||
               uri.Scheme != "https")`
to
`if(uri.Scheme != "http" &&
               uri.Scheme != "https")`

**Comment by lkischler** [comment]
Fixed in 3.0 https://github.com/tomaszzmuda/Xabe.FFmpeg/pull/107
