### ISSUE TITLE
Conversion.Start never completes with WebStream

### ISSUE THREAD

**Issue by woellij** [tomaszzmuda/Xabe.FFmpeg#131]
Hello everybody,

i'm regularly facing the issue, that conversion.start never completes when using a WebStream.

Unfortunately it's not reproducable reliably, hence i'm still investigating a possible explanation on my side, but maybe someone has faced the issue already and knows a solution.
Maybe it's related to #70 .

I'll be working up a temporary fix with a file-watcher to determines the completion.

Cheers

**Comment by tomaszzmuda** [comment]
Hi @woellij 
Could you include "UseShortest(true)" in your conversion?
Maybe this will help.

**Comment by woellij** [comment]
Hi @tomaszzmuda 
thanks for the quick response.
Will try that and get back to you with results.

**Comment by woellij** [comment]
I managed to break it down to the ffmpeg output '[https @ 0x55e0a1b19a00] HTTP error 416 Requested Range Not Satisfiable' which seems to be the culprit. Maybe you can handle the error and throw an exception in it's case (and terminate the ffmpeg-process)

So far i've been unable to find a solution for it - there are a few bug reports concerning this (e.g. https://trac.ffmpeg.org/ticket/6885)

**Comment by tomaszzmuda** [comment]
Have you seen this post https://stackoverflow.com/questions/34324725/ffmpeg-seek-calculating-wrong-byte-range with "-seekable 0"? I guess UseShortest didn't work. I would be glad if you will post here your output from FFmpeg. I cannot reproduce this issue, and log will be helpful. 
Does the file work after you get this this HTTP error?
I 'm going to handle this and throw appropriate exception but need more data.
