### ISSUE TITLE
Decoding of audio call (pcap dump) using codecs.

### ISSUE THREAD

**Issue by kchatterjee77** [tomaszzmuda/Xabe.FFmpeg#133]
Does the Xabe .net wrapper support decoding of audio call using codecs? The audio call file is nothing but a pcap dump of rtp. Is there any sample, documentation available? Can I use 
IConversionResult result = await Conversion.Convert(inpuFile, outputMp3File).Start(); ?

what should be the input file format?

**Comment by tomaszzmuda** [comment]
If only FFmpeg support decoding your codec, your example will work.
This is the easiest way to do that. Check out [our documentation](https://xabe.net/product/xabe-ffmpeg/) about streams. Usually, output file name define output codec, but it can be overwrite by SetCodec method.
