### ISSUE TITLE
Can't cancel Extractaudio conversion

### ISSUE THREAD

**Issue by D0vid** [tomaszzmuda/Xabe.FFmpeg#135]
Hi there, 
I've been using your library to convert webm audio files to MP3 and it's working like a charm.
Unfortunately I'm having a hard time understanding how I'm supposed to cancel an ongoing conversion.
I'm somewhat of a beginner dev so it's quite possible I may just be doing something incredibly stupid without realising 

```csharp
public async Task ConvertToMp3(Download download)
        {   
            try
            {
                var audioOutput = Path.ChangeExtension(download.DownloadPath, FileExtensions.Mp3);
                var conversion = Conversion.ExtractAudio(download.DownloadPath, audioOutput);
                conversion.OnProgress += (sender, args) => download.Progress = 30 + (int) (Math.Round(args.Duration.TotalSeconds / args.TotalLength.TotalSeconds, 2) * 70);
                await conversion.Start(download.ConversionCancellationSource.Token);
            }
            catch (TaskCanceledException ex)
            {
                download.DownloadCancellationSource.Dispose();
                download.DownloadStatus = DownloadStatus.Cancelled;
                throw;
            }
        }

private async Task DownloadVideo(Video v)
        {
            var download = new Download(v);
            if (!CurrentDownloads.Contains(download) && !FileAlreadyExists(download))
            {
                CurrentDownloads.Add(download);
                Task downloadTask = Task.Run(() => _downloader.DownloadVideoAsync(download), download.DownloadCancellationSource.Token);
                Task conversionTask = downloadTask.ContinueWith(antecedant => _converter.ConvertToMp3(download), download.ConversionCancellationSource.Token);
                try
                {
                    await downloadTask;
                    await conversionTask;
                }
                catch (OperationCanceledException ex)
                {
                    download.DownloadStatus = DownloadStatus.Cancelled;
                }
            }   
        }
```

When I run this code and cancel an ongoing conversion like this

```csharp

private void CancelDownload(Download download) => download.Cancel();

public void Cancel()
        {
            if (DownloadStatus == DownloadStatus.Converting)
            {
                ConversionCancellationSource.Cancel();
            } else if (DownloadStatus == DownloadStatus.Downloading)
            {
                DownloadCancellationSource.Cancel();
            }
        }
```

The exception is never caught and another exception makes visual studio enter break mode.
An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
No process is associated with this object.
![image](https://user-images.githubusercontent.com/42772925/44866682-35064a80-ac86-11e8-854c-3e142c910328.png)

I've tried to understand what is happening, looked around the net but to result ... Could this be caused by a bug in the library? 

EDIT : Cancelling the download task works fine, and is done by using another library

**Comment by tomaszzmuda** [comment]
Hi @D0vid,
It's bug in Xabe.FFmpeg.
Some time ago, there was an issue. You wasn't able to stop FFmpeg process if it stucks.
We added check, if Process still exists kill it. But it turned out that raises uncatched exception.
It was hard to test because asynchronous nature of cancellationToken.
Thank you for detailed example, it will be fixed in few hours.

**Comment by D0vid** [comment]
No problem , thank you for your fast answer and for the fix !

**Comment by D0vid** [comment]
Hello again @tomaszzmuda , cancellation works fine now except it doesn't throw a TaskCanceledException or OperationCanceledException when it happens, is this behaviour intended? I'd very much like to catch such an exception in order to perform the necessary tasks (deleting unfinished mp3 in my case)

**Comment by tomaszzmuda** [comment]
Good point. This will be finished in few hours.
