### ISSUE TITLE
Sending own arguments to ffprobe

### ISSUE THREAD

**Issue by AeonDave** [tomaszzmuda/Xabe.FFmpeg#138]
As docu states i can pass own arguments to ffmpeg with

await new Conversion().Start(arguments);

but how i can pass custom arguments to ffprobe? (or there is a method implemented?)
i need to find the keyframes timestamp for a better splitting algorythm
(ffprobe -loglevel error -skip_frame nokey -select_streams v:0 -show_entries frame=pkt_pts_time -of csv=print_section=0 input.mp4)

Thanks

**Comment by tomaszzmuda** [comment]
Hi @AeonDave 

Unfortunately, it is impossible to pass own arguments to FFprobe. 
It will be a nice feature. Definitely, I'll add this.
It requires to expose RunProcess from FFprobeWrapper, change names to looks like from FFmpeg and handle errors. Not much to do. I should do this next week.
Of course feel free to add this by your own by pull request :)

**Comment by AeonDave** [comment]
ok thank you!

**Comment by lkischler** [comment]
Hello @AeonDave

We added this feature for you (nuget package is just available). Look at "Probe" class and "Getting metadata from media file" section in our documentation.

Thanks for your suggestion and we hope using Xabe.FFpeg help you in development ;)

**Comment by AeonDave** [comment]
Well wow thank you!
you are "Top" xD
