### ISSUE TITLE
MediaInfo.Get() throw exception 

### ISSUE THREAD

**Issue by kzwr** [tomaszzmuda/Xabe.FFmpeg#139]
Hello,i very love this lib,thanks you.
today,i want to get music file info by MediaInfo.Get(),but this function throw exception
![image](https://user-images.githubusercontent.com/15187811/45490314-59d7e300-b799-11e8-9683-2667ace6b366.png)
![image](https://user-images.githubusercontent.com/15187811/45490447-af13f480-b799-11e8-8998-460058f733fc.png)

this is the music file : https://drive.google.com/open?id=1xribVkgpmUK7CPACBGxgigkwSkW8YZgp

**Comment by tomaszzmuda** [comment]
I'm so sorry but I cannot reproduce this issue.
My OS doesn't support this character set. But I found one difference.
`{
    "format": {
        "filename": "C:\\Users\\tzmuda\\Downloads\\test.mp3",
        "nb_streams": 1,
        "nb_programs": 0,
        "format_name": "mp3",
        "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
        "start_time": "0.000000",
        "duration": "312.095075",
        "size": "12483803",
        "bit_rate": "320000",
        "probe_score": 51,
        "tags": {
            "title": "´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż┬╝´┐Ż´┐Ż´┐Ż´┐ŻQQ´┐Ż´┐Ż190858230´┐Ż",
            "artist": "´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż┬╝´┐Ż´┐Ż´┐Ż´┐ŻQQ´┐Ż´┐Ż190858230´┐Ż",
            "comment": "´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż┬╝´┐Ż´┐Ż´┐Ż´┐ŻQQ´┐Ż´┐Ż190858230´┐Ż"
        }
    }
}`

At the end of lines with title, artist and comment I have quotations marks. In your example they missing.
If you could pass this to command line and check if output json will look the same.
`ffprobe -v quiet -print_format json -show_format D:\ffmpegTemp\test.mp3`

**Comment by kzwr** [comment]
> 
> 
> I'm so sorry but I cannot reproduce this issue.
> My OS doesn't support this character set. But I found one difference.
> `{ "format": { "filename": "C:\\Users\\tzmuda\\Downloads\\test.mp3", "nb_streams": 1, "nb_programs": 0, "format_name": "mp3", "format_long_name": "MP2/3 (MPEG audio layer 2/3)", "start_time": "0.000000", "duration": "312.095075", "size": "12483803", "bit_rate": "320000", "probe_score": 51, "tags": { "title": "´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż┬╝´┐Ż´┐Ż´┐Ż´┐ŻQQ´┐Ż´┐Ż190858230´┐Ż", "artist": "´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż┬╝´┐Ż´┐Ż´┐Ż´┐ŻQQ´┐Ż´┐Ż190858230´┐Ż", "comment": "´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż´┐Ż┬╝´┐Ż´┐Ż´┐Ż´┐ŻQQ´┐Ż´┐Ż190858230´┐Ż" } } }`
> 
> At the end of lines with title, artist and comment I have quotations marks. In your example they missing.
> If you could pass this to command line and check if output json will look the same.
> `ffprobe -v quiet -print_format json -show_format D:\ffmpegTemp\test.mp3`

![image](https://user-images.githubusercontent.com/15187811/45528154-a52dd800-b811-11e8-9596-346be97fba80.png)

in RunProcess function, i add code “StandardOutputEncoding = Encoding.Default;”, this problem is solved

**Comment by tomaszzmuda** [comment]
@kzwr 
I'm glad you find the answer.
I'll test this solution and commit if everything works.
