### ISSUE TITLE
FFprobeWrapper GetVideoAspectRation Crash when splitted video get probed

### ISSUE THREAD

**Issue by AeonDave** [tomaszzmuda/Xabe.FFmpeg#141]
Hello.

After a command like 
ffmpeg -i in.mp4 -codec copy -f segment -segment_list out.csv -segment_time 3 out%03d.nut

a command like 
Xabe.FFmpeg.MediaInfo.Get(input).ConfigureAwait(false);

crash beacuse

file: FFprobeWrapper.cs
```
private string GetVideoAspectRatio(int width, int heigght)
        {
            int cd = GetGcd(width, heigght);
            return width / cd + ":" + heigght / cd;
        }

```
width and heigght are both 0.
cd has 0 as result and then there is a division by 0.

this is a ffprobe result of that file 

```
[mpeg4 @ 000001d6518de880] time_increment_bits 0 is invalid in relation to the current bitstream, this is likely caused by a missing VOL header
[mpeg4 @ 000001d6518de880] time_increment_bits set to 10 bits, based on bitstream analysis
[mpeg4 @ 000001d6518de880] time_increment_bits 4 is invalid in relation to the current bitstream, this is likely caused by a missing VOL header
[mpeg4 @ 000001d6518de880] time_increment_bits set to 10 bits, based on bitstream analysis
[mpeg4 @ 000001d6518de880] looks like this file was encoded with (divx4/(old)xvid/opendivx) -> forcing low_delay flag
[mpegts @ 000001d6518dd400] decoding for stream 0 failed
[mpegts @ 000001d6518dd400] Could not find codec parameters for stream 0 (Video: mpeg4 ([16][0][0][0] / 0x0010), yuv420p): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'C:\temp\encoder\57ae3e7b-e2ed-49b4-8b08-2e56d3a64fc9\MsMmKbDERrzrwJA1\MsMmKbDERrzrwJA1_0.ts':
  Duration: 00:00:03.20, start: 1.400000, bitrate: 1143 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: mpeg4 ([16][0][0][0] / 0x0010), yuv420p, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Stream #0:1[0x101](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 124 kb/s
```

the file isn't broken because has been splitted into chunks for hls online video

can be solved with 
if (cd <= 0) return $"{0}:{0}";

**Comment by lkischler** [comment]
Hello @AeonDave,
We should write unit test for this fix so we need some file to test it. Can you share some sample (really small) to test it? Or if you can't share any media file can you tell us how to generate this file??

**Comment by AeonDave** [comment]
hello!
i just launched a -i {Input} -c copy -map 0 -f segment -segment_time {duration} -segment_list_type m3u8 -segment_list chunklist.m3u8 {Output} on a old mpeg video. unfortunatly i'm not having access to that file but when i debugged your code i simply found out that ffmpeg failed to retrive w:h values which were in fact 0.

**Comment by tomaszzmuda** [comment]
#142
