### ISSUE TITLE
Is it possible to change video source during stream?

### ISSUE THREAD

**Issue by nonpensavo** [tomaszzmuda/Xabe.FFmpeg#144]
Currently Im using process with ffmpeg but could not manage to change video/audio input on fly, and looking for other solutions/wrappers which might possibly do that. e.g. if I start streaming using my webcam and mic to wowza  servers and switch to another camera or 'desktop capture' on fly with no audio interruptions. And other delays. Thanks

**Comment by tomaszzmuda** [comment]
I don't know how to solve this.
Maybe starting record the stream in background and just changing the screen after it connects will be enough?
