### ISSUE TITLE
Option to set a custom number of threads

### ISSUE THREAD

**Issue by shravan2x** [tomaszzmuda/Xabe.FFmpeg#146]
Right now, the `IConversion.UseMultiThread` options only allows boolean values and forces either all cores to be used or just one. Using `AddParameter("-threads 2")` doesn't work either since the build string then contains multiple `-threads` parameters.

There are many cases when a custom number of cores is preferred:
- In hyper-threaded systems, it's better to use the number of physical cores, not logical ones.
- The user might want the conversion to be a background process, and so use a fewer number of cores.

**Comment by tomaszzmuda** [comment]
Hello @shravan2x 
You are right. I'll change this soon.

**Comment by tomaszzmuda** [comment]
#147 - should be on nuget in one-two days :)

**Comment by tomaszzmuda** [comment]
It' done!
