### ISSUE TITLE
Danger of Task.Run to make ffmpeg async

### ISSUE THREAD

**Issue by jawadatgithub** [tomaszzmuda/Xabe.FFmpeg#15]
It seems you are using Task.Run to run System.Diagnostics.Process
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/master/Xabe.FFmpeg/FFmpeg.cs#L41
 
Based on this link: https://stackoverflow.com/questions/14896057/mvc4-webapi-process-launcher
and many online references using Task.Run in asp.net or .net core api controller is dangerous: quoting below from @StephenCleary

> However, I must caution you that this is quite dangerous. ASP.NET is an HTTP server, so if there are no active requests, it will feel free to take down your AppDomain if it wants to. This would mean your "do more stuff with exitcode" will just drop off the face of the earth.

I myself looking for simple solid solution other than https://github.com/HangfireIO/Hangfire

Are you aware of this issue?

**Comment by tomaszzmuda** [comment]
I'll consider change method of running conversion.
But ASP.NET apps shoudn't do such a CPU consuming processes.
If you want to use this library in ASP.NET project, conversions shoudn't take more than few seconds.
In this case HTTP server won't kill process.
Best way to convert files is to make external application which dequeue processing files and do it one by one like Azure WebJob [https://docs.microsoft.com/en-us/azure/app-service/web-sites-create-web-jobs](url).
I'll try to find better solution anyway.
Thank you for reporting this.
If you have more suggestions feel free to make more issues.

**Comment by jawadatgithub** [comment]
I have .net core API requirement to concat up to 12 videos with Max duration of 4 hours, sure that's would take few minutes which acceptable by the client as long its async and functioning.

I can't use online services or public clouds as the client operates in isolated network.

**Comment by StephenCleary** [comment]
To clarify, using `Task.Run` in ASP.NET is only dangerous *if the returned task isn't awaited*. In this case, it *is* awaited, so it's not dangerous - just a little less efficient than if it was run directly.

Also, I'm in total agreement with @tomaszzmuda that video conversions shouldn't generally be done in ASP.NET at all anyway, regardless of how they're called. Ideally, a separate backend process is used; I usually recommend (in decreasing order of preference):

- Azure Functions
- Azure WebJobs
- Azure Worker Roles
- Win32 services

If you're not interested in setting up Azure Stack, then I'd recommend creating a Win32 service to run your ffmpeg jobs.

**Comment by jawadatgithub** [comment]
@StephenCleary my requirements to deploy the API on centOS, so it can be back-end service (not sure if win32 service is valid term in .net core 2!)

 Thanks for clarifying the not dangerous bit.

**Comment by StephenCleary** [comment]
A daemon, then.
