### ISSUE TITLE
Does Xabe support URLs as inputs?

### ISSUE THREAD

**Issue by casperOne** [tomaszzmuda/Xabe.FFmpeg#157]
I like the design of Xabe, and I am evaluating it for use in a video pipeline project that I'm developing.

That said, we will be pulling streams from a URL (which we can do from the command line), but it doesn't seem like there's support for it in Xabe for using URLs as inputs (it all seems to go through a `FileInfo` instance which bombs when given a URL).

Is it possible to build commands with Xabe which use URLs (even if I have to manually splice it in later)?

**Comment by tomaszzmuda** [comment]
Hi @casperOne 
Have you checked the WebStream class?
I'm not sure what do you want to do but if you tell URL - that is class to handle videos from URLs.
