### ISSUE TITLE
Snapshots and generic conversions using AddParameter don't work.

### ISSUE THREAD

**Issue by Arkasian** [tomaszzmuda/Xabe.FFmpeg#159]
I've tried ```Converision.Snapshot()``` method and ```Conversion.AddParameter()``` method to make a snapshot using this ffmpeg commands(which works if invoked from bash!):
```ffmpeg -i video.webm -ss 00:00:07.000 -vframes 1 thumb.jpg```. 
Neither the first one nor the second one option works for me.
No exceptions caught or uncaught, no print outs from library, no DataReceived event raised, no OnProgress event raised, totally nothing. 
**Working on .NET Core 2.2b104.**
**P.S**: I've read that the lib is mainly for .NET standard but even in your description on this repo it is said that Conversion using AddParameter() should work even for Core so what is really going on here?

**Comment by lkischler** [comment]
Hello,
I created test to check snapshots on *.webm extension and everything works ok (look this - [commit](https://github.com/tomaszzmuda/Xabe.FFmpeg/compare/159_Snapshots_and_generic_conversions_using_AddParameter_dont_work?expand=1)). Can you show your code?? Probably you don't wait for result from async functions.

About P.S section: lib is build as .NET standard so should work with .NET Core and it's not strength [(more here)](https://social.msdn.microsoft.com/Forums/vstudio/en-US/7035edc6-97fc-49ee-8eee-2fa4d040a63b/what-are-differences-between-net-framwork-net-standard-and-net-core?forum=clr).

**Comment by Arkasian** [comment]
Im using the exact sample from your own docs so wtf? Am awaiting using async/await so no way that there is a problem with threading, even then I should receive null as a result and I dont receive anything.

**Comment by tomaszzmuda** [comment]
@Arkasian 
Could you please provide us sample of your code and/or this video file? We are trying to investigate the issue but cannot reproduce issue.
