### ISSUE TITLE
Where is StandardOutput stream output?

### ISSUE THREAD

**Issue by jawadatgithub** [tomaszzmuda/Xabe.FFmpeg#16]
In https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/master/Xabe.FFmpeg/FFmpeg.cs#L49

`Process.ErrorDataReceived += ProcessOutputData;`

But where is:
`Process.OutputDataReceived += ProcessOutputData;`

Also can you explain the following line of code:
`OnDataReceived?.Invoke(this, e);`

**Comment by tomaszzmuda** [comment]
Process.OutputDataReceived += ProcessOutputData;
Is redundand.
All of ffmpeg output come from error output.
So if you want to process raw output from FFmpeg just add listener to OnDataReceived event.
In event args you have line from FFmpeg output. It fires only when are listenes on that event.
