### ISSUE TITLE
How to do desktop capture

### ISSUE THREAD

**Issue by sdcb** [tomaszzmuda/Xabe.FFmpeg#160]
This should be done with `ffmpeg -f dshow -i video="screen-capture-recorder" output.mkv` in command line. 

Wondering is there any more user-friendly way to do that?

**Comment by tomaszzmuda** [comment]
Right now, you cannot achive this by built-in method in Xabe.FFmpeg.
But it's nice enhancement, will be added soon :)

**Comment by 06needhamt** [comment]
The provided method of desktop capture seems to be platform specific as it requires a DirectShow device so there might have to be different methods for each platform with the appropriate method being determined and called at runtime. I am Interested in implementing this as it is a feature that would be very useful to me.

**Comment by 06needhamt** [comment]
I added basic desktop capture functionality with #182
