### ISSUE TITLE
Wrong order of ffmpeg parameters for Conversion.Snapshot

### ISSUE THREAD

**Issue by Unavi** [tomaszzmuda/Xabe.FFmpeg#161]
Calling `var result = Conversion.Snapshot(originalPath, newPath, TimeSpan.FromSeconds(60));
            await result.Start();` generates these parameters for ffmpeg:

-i "originalPath" -n -threads 8 -codec:v png -ss 00:01:00 -frames:v 1 -map 0:0 "newPath"
I think it should generate:
-ss 00:01:00 -i "originalPath" -n -threads 8 -codec:v png -frames:v 1 -map 0:0 "newPath"
because otherwise ffmpeg decodes everything until that point, which takes significantly longer. 
[Source (FFMPEG doc)](https://trac.ffmpeg.org/wiki/Seeking)

**Comment by lkischler** [comment]
Chenges [(pull request)](https://github.com/tomaszzmuda/Xabe.FFmpeg/pull/162) are merged to master branche so nuget package will be available soon. Check version 3.1.6 ;)
