### ISSUE TITLE
await MediaInfo.Get(path) stuck forever

### ISSUE THREAD

**Issue by Unavi** [tomaszzmuda/Xabe.FFmpeg#163]
Since 3.1.6 await MediaInfo.Get(path) is stuck for certain files.
One of the files is this mp4: https://we.tl/t-NoPpf5FQP2
With 3.1.5 it runs through fine.

**Comment by lkischler** [comment]
Hello,
Thanks for open this issue. I checked this and you're right. It is something wrong with proccess and waiting for exit. For some files (e.g. yours) exit event doesn't fire.  I will try fix it as soon as possible.

**Comment by 06needhamt** [comment]
@lkischler Hi I have done some testing on this issue and it seems to occur only when a file contains more than one of a type of stream. For example if a file has more than one video stream the issue occurs or if a file has more than one audio stream but only one video stream the issue also occurs. This issue does not seem to be affected by subtitle streams and all files that I have tested which only have one video stream and one audio stream all seem to work.

Let me know if you need any sample files or any more testing

Hope this helps you fix the issue.

**Comment by lkischler** [comment]
Hello,
I don't understand why Process.WaitForExit() block output stream (sometimes) but I patched it for now. Every tests (include test with your file) passed so everything will work fine. I will debug it with .NET Reflector next week to investigate why that didn't work that I expected. 

I'm waiting for your feedback from tests on version 3.1.7.

**Comment by 06needhamt** [comment]
@lkischler I tested version 3.1.9 again today with all the same files I used on 3.1.6 and they all processed correctly with no issues.

**Comment by lkischler** [comment]
Great. So I'm closing this issue.
