### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object. when trying to Snapshot()

### ISSUE THREAD

**Issue by iscorekin** [tomaszzmuda/Xabe.FFmpeg#165]
Hi, i have this error when trying to get snapshot: `NullReferenceException: Object reference not set to an instance of an object.`

`FFmpeg.ExecutablesPath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "ffmpeg");
 Conversion.Snapshot(videoFile, image, TimeSpan.FromSeconds(1)).Start();`

`videoFile` and `image` contains path to video and image.

What I'm doing wrong?

**Comment by lkischler** [comment]
Hello,
Are you sure that file has video streams?? To debug it you can configure your own conversion (copy code from helper) instead of using helper:         

            
            IMediaInfo info = AsyncHelper.RunSync(() => MediaInfo.Get(inputPath));
            IVideoStream videoStream = info.VideoStreams.FirstOrDefault()
                                           .SetCodec(VideoCodec.Png)
                                           .SetOutputFramesCount(1)
                                           .SetSeek(captureTime);
            return New()
                .AddStream(videoStream)
                .SetOutput(outputPath);`

It will help us to resolve this issue.

**Comment by iscorekin** [comment]
@lkischler I did that, so [here](http://scratchpad.io/black-and-white-fog-3480) is full stack trace from my app, when i'm trying to get snapshot.

**Comment by lkischler** [comment]
Hello, it is probably referenced with #166 which is currently closed so please check the newest version of library.

**Comment by iscorekin** [comment]
Ok, thanks!

**Comment by 06needhamt** [comment]
@iscorekin Are you still experiencing this issue? I seemed to get this intermittently with certain files however, since I upgraded to the latest release I haven't seen this issue occur.
