### ISSUE TITLE
No such process

### ISSUE THREAD

**Issue by felixwan-git** [tomaszzmuda/Xabe.FFmpeg#166]
Hi, I found an exception by debugging the code, NO such process. When Process executes too fast, Process.GetCurrentProcess will throw No such process exception, because process has exited.

This is my code.
![image](https://user-images.githubusercontent.com/45676208/56876567-e6aa8500-6a7a-11e9-99db-aa55c26b1468.png)
Throw exception  When Converting .mp4 file to .ts file. 
mp4 file size: 2.3M

![image](https://user-images.githubusercontent.com/45676208/56875889-21f68500-6a76-11e9-86da-a3f647594d35.png)

**Comment by felixwan-git** [comment]
![image](https://user-images.githubusercontent.com/45676208/56876054-4e5ed100-6a77-11e9-9d8e-480fae083c42.png)
This is a screenshot of the thrown exception

**Comment by lkischler** [comment]
Hello, thank you for this report. Probably it is easy to fix it so I will do that today or tommorow.

**Comment by felixwan-git** [comment]
Thanks, This is really easy to solve. 
when use nuget package, It's not throw an exception, it's will be blocking. so i fork project what is happen. and i'm try to solve this, and it work be ok! 
this is my solve:
![image](https://user-images.githubusercontent.com/45676208/56884450-6a289e00-6a9c-11e9-8cd6-d6fab940b6e4.png)

if you need, I will commit pr.

**Comment by lkischler** [comment]
Yes it is one of the fastest way to fix it. Maybe is it possible to prevent this exception?? If you want fix it feel free to make pr ;)

**Comment by lkischler** [comment]
It's merged now so I'm closing this.
