### ISSUE TITLE
Conversion raises not valid application exception

### ISSUE THREAD

**Issue by Unavi** [tomaszzmuda/Xabe.FFmpeg#168]
I tried to use the library to generate previews from a video in my WPF application (.net framework 4.7.2). The conversion always raises the following exception:
`
The specified executable is not a valid application for this OS platform.
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at bool System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at bool System.Diagnostics.Process.Start()
   at Process Xabe.FFmpeg.FFmpeg.RunProcess(string args, string processPath, Nullable<ProcessPriorityClass> priority, bool standardInput, bool standardOutput, bool standardError)
   at Task<bool> Xabe.FFmpeg.FFmpegWrapper.RunProcess(string args, CancellationToken cancellationToken)+() => { } [0]
   at async Task<IConversionResult> Xabe.FFmpeg.Conversion.Start(string parameters, CancellationToken cancellationToken)`

I am loading the ffmpeg library with Xabe.FFmpeg.FFmpeg.GetLatestVersion();.
Before the conversion I am running var mediaInfo = await MediaInfo.Get(originalPath); which works fine. Additionally I am using your library in a mvc core project and there the exact same calls work. 

Any idea why it raises this exception in my WPF application?

**Comment by 06needhamt** [comment]
I am also experiencing this issue when running the unit tests on my personal computer however my work computer works fine. 

Let me know If i can assist in any way.

**Comment by Unavi** [comment]
I integrated Xabe.FFmpeg into one of my other WPF applications and there it works fine. I compared all the settings of the project but they are the same. The only difference between the two projects is: in the working project I directly reference Xabe.FFmpeg and in the not working project I reference a .net standard library which references it. No idea if that makes a difference.

**Comment by tomaszzmuda** [comment]
Could you share the not working sample?

**Comment by Unavi** [comment]
https://drive.google.com/open?id=1yMho_xJIxirmDE5PydHybWRhJBk0THQ9
I removed everything and added one button back in. It should convert the MP4_2.mp4 into a Thumb.png in the bin folder. Currently I am using the shared ffmpeg ddls but it generates the same exception with the static dlls.

**Comment by tomaszzmuda** [comment]
@lkischler found the issue :)
When Xabe.FFmpeg tried to get FFmpeg executable, the first file started with "FFmpeg" was FFmpeg.AutoGen.dll 
We will fix this in the PR #173
This change should be in version 3.2, available probably on Monday
