### ISSUE TITLE
Normalize and refactor changing speed of video and sound feature

### ISSUE THREAD

**Issue by lkischler** [tomaszzmuda/Xabe.FFmpeg#17]
I suggest to normalize methods ChangeAudioSpeed and ChangeVideoSpeed to the same parameter meaning, add one method with synchronized change of video and audio speed, protect parameters range (probably from 0.5 to 2) and maybe automate changing speed with other values.

**Comment by tomaszzmuda** [comment]
[Commit link](https://github.com/tomaszzmuda/Xabe.FFmpeg/commit/836299cbbb92190e3968037128118cd3a1d238e4)
Done.
Please tell me if it satisfied you.
