### ISSUE TITLE
Add Ability to Force Aspect Ratio

### ISSUE THREAD

**Issue by 06needhamt** [tomaszzmuda/Xabe.FFmpeg#174]
Xabe.FFmpeg should have the ability to force the aspect ratio of the video when resizing and fill in empty space with bars if the ratios do not correctly scale. This can be achieved with the following filtergraph.

``` c#
private string BuildForceAspectRatioFilter(int outputWidth, int outputHeight)
{
    return string.Format("\"scale=w={0}:h={1}:force_original_aspect_ratio=1,pad={0}:{1}:(ow-iw)/2:(oh-ih)/2\"", outputWidth, outputHeight);
}
```

I am happy to implement this in unless you have any comments.

**Comment by tomaszzmuda** [comment]
Cannot you achive this by using SetScale method?

**Comment by 06needhamt** [comment]
The SetScale function only sets the width and height of the video i.e this part of the filtergraph `scale=w={0}:h={1}` but as far as I can see there is currently no way to easily maintain aspect ratio or pad out the extra space to ensure the ratio is maintained as accomplished by this filtergraph. `force_original_aspect_ratio=1,pad={0}:{1}:(ow-iw)/2:(oh-ih)/2` Let me know if i missed anything.

**Comment by 06needhamt** [comment]
Closing as this is now possible using the v4 api
