### ISSUE TITLE
input parameters

### ISSUE THREAD

**Issue by Gamingdevil** [tomaszzmuda/Xabe.FFmpeg#179]
Is there any support for input parameters besides SetSeek? I need to stream to a network endpoint in real time and would like to use the `-re` input flag, but I can't find a way to add any, besides seek.

I know I can just build the whole param string by myself, but then it seems redundant to use Xabe in the first place.

**Comment by tomaszzmuda** [comment]
Hi @Gamingdevil 
Have you tried AddParameter on IConversion object?

**Comment by Gamingdevil** [comment]
> Have you tried AddParameter on IConversion object?

@tomaszzmuda 
I have and get the following error:

> Option re (read input at native frame rate) cannot be applied to output url -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.

As I understand it, FFmpeg only allows certain parameters on the input file and `-re` is one of them. If it would be added after the output file, it appears to be ignored. 
The problem is that the only (supported) input parameter I can currently find in Xabe.FFmpeg is the seek (ss) parameter, for which the SetSeek method (understandably) only allows a TimeSpan.

Thanks for taking the time to answer my question.

**Comment by tomaszzmuda** [comment]
Could you write all parameters that you are trying to pass to FFmpeg?
I'll reproduce issue and try to solve it :)

**Comment by Gamingdevil** [comment]
@tomaszzmuda 
This is the actual command that works
`ffmpeg -re -i "c:\temp\somewavfile.wav" -acodec libmp3lame -f rtp rtp://127.0.0.1:3030`
I have VLC listening on rtp://@3030, but you can also setup an ffmpeg listener through `ffplay rtp://127.0.0.1:3030`

The code I (would like to) use is:
`var audioStream = (await MediaInfo.Get(fileName)).AudioStreams.FirstOrDefault();`
`if (audioStream == null) return;`
`if (((AudioStream)audioStream).Codec == null) audioStream.SetCodec(new AudioCodec("libmp3lame"));`
`var conversion = Conversion.New().AddParameter("-re").AddStream(audioStream).AddParameter("-f rtp").SetOutput($"{_endpoint.AbsoluteUri}");`
`await conversion.Start();`
but then I get the error shown above.

If I leave out the "-re" parameter, it works, but the desired realtime streaming doesn't work.

**Comment by Gamingdevil** [comment]
Hi @tomaszzmuda 
I was wondering if you had already had a chance to try and reproduce the issue. Right now I got everything to work by invoking ffmpeg.exe directly but I would prefer to be able to use Xabe as it makes for cleaner code.

Unfortunately there's no point if I can't stream in realtime.

**Comment by tomaszzmuda** [comment]
@Gamingdevil 
Sorry for long delay. Work is in progress #180

**Comment by Gamingdevil** [comment]
> Sorry for long delay. Work is in progress #180
Alright, thank you

**Comment by tomaszzmuda** [comment]
Changes was deployed few days ago. Have you checked if it work for your case?

**Comment by Gamingdevil** [comment]
I have not, but I will give it a shot today.

**Comment by Gamingdevil** [comment]
Appears to work beautifully with similar performance as the process I was spinning up manually. With the cleaner code as well as extended possibilities of Xabe, I will definitely prefer it to my temporary solution.

Thanks for the help and quick response.
