### ISSUE TITLE
Protect conversion/connect videos in unsupported formats

### ISSUE THREAD

**Issue by lkischler** [tomaszzmuda/Xabe.FFmpeg#18]
When I try join few videos in different formats and I use e.g *fly video conversion will freeze. Is possible to catch that and throw some exception or end conversion with error?

**Comment by tomaszzmuda** [comment]
Could you reproduce it in today version of repository (14.10)?
Could you specify more details, best option will be your conversion object settings.

**Comment by lkischler** [comment]
Parameters (all files from ):
 
            var input0Path = Path.Combine("C:\\", "samples", "video.mp4");
            var input1Path = Path.Combine("C:\\", "samples", "video0.mp4");
            var input2Path = Path.Combine("C:\\", "samples", "video1.mkv");
            var input3Path = Path.Combine("C:\\", "samples", "video2.flv");
            var outputPath = Path.Combine("C:\\", "samples", "result.mp4");

this one works good:

           var conversion = new Conversion()
                .SetOutput(outputPath)
                .Concat(input0Path, input1Path)
                .Start();

this one returns strange result (about 10% of second video is added):

           var conversion = new Conversion()
                .SetOutput(outputPath)
                .Concat(input0Path, input2Path)
                .Start();

this one return only first file (last week this one freeze):

           var conversion = new Conversion()
                .SetOutput(outputPath)
                .Concat(input0Path, input3Path)
                .Start();

It is possible that concat files in different formats is unsupported in ffmpeg but then I expect some error with information.

**Comment by lkischler** [comment]
by ConversionHelper everything works good

**Comment by tomaszzmuda** [comment]
I have added validation and comment to Xabe.FFmpeg.Conversion.Concat.
Please tell me if everything works in your case.
