### ISSUE TITLE
.net framework 4.6.1 error

### ISSUE THREAD

**Issue by volgabar** [tomaszzmuda/Xabe.FFmpeg#189]
Hi, 
We are migrating our project .net core to .net framework.
Before migrating we had no problem with code block below.

```
IMediaInfo mediaInfo = await MediaInfo.Get(_configuration.VideoPath + "\\" + videoName);
result = mediaInfo.VideoStreams.First().Duration.TotalSeconds;
```

nuget version 3.4.0 and ffmpeg version 4.1.4
ffmpeg.exe and ffprobe.exe added project path and copy to output directory switched to Copy always. Now even if we fulfilled this condition
     - FFmpeg executables have to be in the same directory with application executable
get this error:
     - Cannot find FFmpeg in PATH. This package needs installed FFmpeg. Please add it to your PATH variable or specify path to DIRECTORY with FFmpeg executables in FFmpeg.ExecutablesPath

after added this code to global.asax we dont get it
`FFmpeg.ExecutablesPath = System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().GetName().CodeBase);`

but this time we get this error for same code.
- URI formats are not supported.

Thanks in advance.

**Comment by tomaszzmuda** [comment]
Hello.

Are you sure that **_configuration.VideoPath** is not empty? In this case your file path will looks like "\\video.mp4" and can cause problem with URI format.
Could you pass absolute path to video and/or ffmpeg?

**Comment by volgabar** [comment]
![image](https://user-images.githubusercontent.com/16306638/62703959-0266e500-b9f3-11e9-95dc-579e46706c8d.png)

yeah i am. I passed the absolute path and still the same. I can get a response for the same path with .net core project 
![image](https://user-images.githubusercontent.com/16306638/62704949-34794680-b9f5-11e9-8cf3-f60e778d3e80.png)

**Comment by tomaszzmuda** [comment]
Strange. Could you give me whole exception with the callstack? I need to know the line where the exception occurs. 
I don't know if it will be available for nuget package. If you could please download the repository and try to use it instead of nuget package. All debug symbols will be available

**Comment by volgabar** [comment]
at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at System.IO.DirectoryInfo..ctor(String path)
   at Xabe.FFmpeg.FFmpeg..ctor()
   at Xabe.FFmpeg.MediaInfo.<Get>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProjctName.Controllers.DeviceSettingsController.<GetVideoLengthAsync>d__11.MoveNext() in C:\Users\user\Desktop\Projects\ProjctName\ProjctName\Controllers\DeviceSettingsController.cs:line 171

I will add repository and return result

**Comment by tomaszzmuda** [comment]
I suppose that the problem is in .NET Framework and the letters in your filename. Will it work when filename doesn't contain any "special" characters?

**Comment by volgabar** [comment]
It hasn't worked for filename 'abc.mp4'.

**Comment by tomaszzmuda** [comment]
Does FFmpeg.ExecutablesPath in your case started from "file:\\"?
Maybe CodeBase is not the best option. Look at this article:
https://stackoverflow.com/questions/10488277/why-cant-my-application-open-a-file-that-exists
You could try to use this:
System.IO.Path.GetDirectoryName(Application.ExecutablePath)
