### ISSUE TITLE
App freeze when output file exists

### ISSUE THREAD

**Issue by lkischler** [tomaszzmuda/Xabe.FFmpeg#19]
When I try to get snapshot and output file just exists conversion will freeze. I expect some exception or break with error.

**Comment by tomaszzmuda** [comment]
Done.
Now before the FFmpeg process starts, it's validate if output file exists.
If exists return IOException.
[Commit link](https://github.com/tomaszzmuda/Xabe.FFmpeg/commit/2a332bb75d13735218757dc2f6dc5994cc6fc978)
