### ISSUE TITLE
'System.AggregateException' when doing sequential Conversions

### ISSUE THREAD

**Issue by Kjos** [tomaszzmuda/Xabe.FFmpeg#192]
I included code below. Running the Conversions (between the curly brackets) separately works fine, but running them directly after each other gives a:

```
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll
```
This is using the very latest FFmpeg downloaded from the website (master branch).

I'm looking to implement Xabe in my commercial product. It's nice that there's an FFmpeg downloader and FFprobe support, saves me some hassle. It's too bad the Concatenate function relies solely on filters; it would've been nice to have demuxer concat capability.

```

    class Video2Video
    {

        private string path;
        private string savePath;

        public Video2Video(string path, string savePath)
        {
            this.path = path;
            this.savePath = savePath;
        }

        public async Task WorkAsync()
        {
            FFmpeg.ExecutablesPath = "Assets/ffmpeg/bin";

            string dir = "ExtractVideo/";
            if (Directory.Exists(dir))
            {
                Directory.Delete(dir, true);
                while (Directory.Exists(dir)) Thread.Sleep(100);
            }
            Directory.CreateDirectory(dir);

            string extension = Path.GetExtension(this.path);
            {
                Console.WriteLine(extension);
                IConversionResult conversionResult = await Conversion.Split(this.path, this.savePath, TimeSpan.FromSeconds(0), TimeSpan.FromSeconds(8)).Start().ConfigureAwait(false);
            }

            {
                while (!File.Exists(this.savePath))
                {
                    Thread.Sleep(100);
                }


                Func<string, string> outputBuilder = (number) => { return Path.Combine(dir, number + FileExtensions.Png); };
                IMediaInfo info = await MediaInfo.Get(this.savePath).ConfigureAwait(false);
                IVideoStream videoStream = info.VideoStreams.First()?.SetCodec(VideoCodec.Png);

                IConversionResult conversionResult = await Conversion.New()
                                                                     .AddStream(videoStream)
                                                                     .ExtractEveryNthFrame(10, outputBuilder)
                                                                     .Start().ConfigureAwait(false);
            }
        }
    }
```

**Comment by Kjos** [comment]
This is on Windows 10, x64

**Comment by Kjos** [comment]
I used the 30mb BuckBunny video from https://www.sample-videos.com/ to test. https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4

**Comment by tomaszzmuda** [comment]
Hello,

Could you provide me more details about this "InvalidOperationException"?

**Comment by Kjos** [comment]
If I remove the file beforehand (savePath), I will get 'Invalid file. Cannot load file: filename' for the second conversion. 

If I do not remove the file before running, I get:
`
InnerException | {"ffmpeg version N-94982-gea673a0edb Copyright (c) 2000-2019 the FFmpeg developers\r\n  built with gcc 9.2.1 (GCC) 20190918\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 35.100 / 56. 35.100\r\n  libavcodec     58. 58.101 / 58. 58.101\r\n  libavformat    58. 32.104 / 58. 32.104\r\n  libavdevice    58.  9.100 / 58.  9.100\r\n  libavfilter     7. 58.102 /  7. 58.102\r\n  libswscale      5.  6.100 /  5.  6.100\r\n  libswresample   3.  6.100 /  3.  6.100\r\n  libpostproc    55.  6.100 / 55.  6.100\r\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from 'xxx\\SampleVideo_1280x720_30mb.mp4':\r\n  Metadata:\r\n    major_brand     : isom\r\n    minor_version   : 512\r\n    compatible_brands: isomiso2avc1mp41\r\n    creation_time   : 1970-01-01T00:00:00.000000Z\r\n    encoder         : Lavf53.24.2\r\n  Duration: 00:02:50.86, start: 0.000000, bitrate: 1474 kb/s\r\n    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1086 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)\r\n    Metadata:\r\n      creation_time   : 1970-01-01T00:00:00.000000Z\r\n      handler_name    : VideoHandler\r\n    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 383 kb/s (default)\r\n    Metadata:\r\n      creation_time   : 1970-01-01T00:00:00.000000Z\r\n      handler_name    : SoundHandler\r\nFile 'xxx/xx.mp4' already exists. Exiting."} | System.Exception {Xabe.FFmpeg.Exceptions.ConversionException}`

 It seems it doesn't want to overwrite the file, that's problem 1. Second it cannot load the saved file and seems to corrupt it even when trying.

**Comment by Kjos** [comment]
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait()\r\n   at TestProject.TestMain.VideoTest() in class.cs:line 250\r\n   at TestProjectAnalyze.Program.Main(String[] args) in Program.cs:line 15" | string

**Comment by Kjos** [comment]
Ah, it seems the corrupting file was my part due to checking if the file was readable. I think the only problem is that it doesn't overwrite the savePath file, but I can get around that by removing it manually.

**Comment by Kjos** [comment]
Problem is solved by deleting file beforehand.
