### ISSUE TITLE
Nuget package behind?

### ISSUE THREAD

**Issue by Kjos** [tomaszzmuda/Xabe.FFmpeg#194]
I'm trying to use the InputBuilder with Conversion.BuildFromImages, but it seems the Nuget package is behind the github, and there isn't an alpha release version.

Could you update the Nuget package to align with the Github? This would also make it easier to traverse code.

I've tried building the project manually but had some problems (also with InputBuilder).

**Comment by tomaszzmuda** [comment]
I triggered new release to nuget right now. New version (3.5.0) should be available in few minutes.
If you still have a problem with InputBuilder I'll investigate what's going on.

**Comment by Kjos** [comment]
Okay, thanks! Will come back with results.

Op vr 20 sep. 2019 om 18:48 schreef Tomasz Żmuda <notifications@github.com>:
