### ISSUE TITLE
RFI: File Checksum

### ISSUE THREAD

**Issue by kellcomnet2** [tomaszzmuda/Xabe.FFmpeg#195]
Both ffmpeg and ffprobe return the checksum via the commandline but i am not finding where it is exposed in your managed code wrapper. Am I overlooking it, or has that not been exposed yet?

ffprobe version 4.2 Copyright (c) 2007-2019 the FFmpeg developers
[snip]
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002cf2d0dc280] [aax] file checksum == b0093ea739a38119fc2cd842e3b1edd757cefab8

[snip]

**Comment by tomaszzmuda** [comment]
I tried to get this checksum but don't see anywhere. Can you write exact command you pass to ffmpeg/ffprobe?

**Comment by kellcomnet2** [comment]
Command text and output below

![image](https://user-images.githubusercontent.com/1731737/65834595-18ca4800-e2a2-11e9-8e96-5d3511521991.png)

**Comment by tomaszzmuda** [comment]
I've got checksum only for aax files.
At this moment it's not supported and we don't have in plans to implements this but feel free to make a Pull Request with changes.

You can achive this by subscribing OnDataReceived event.
