### ISSUE TITLE
GetLatestVersion() not supported for Linux64

### ISSUE THREAD

**Issue by w0ns88** [tomaszzmuda/Xabe.FFmpeg#196]
Hi I am getting the following error:

```
"Error caught: System.NotSupportedException: The automated download of the full FFMpeg package is not supported for the current Operation System: Linux64.
   at Xabe.FFmpeg.Downloader.Zeranoe.FullFFmpegDownloader.GenerateLink()
   at Xabe.FFmpeg.Downloader.Zeranoe.FullFFmpegDownloader.GetLatestVersion()
   at FileCompressor.Controllers.FilesController.CompressToMp4() in /src/FileCompressor/Controllers/FilesController.cs:line 47"
```

It seems that downloading the ffmpeg binaries for ubuntu 16.04 is not working properly. In my code I do the following:

```
FFmpeg.ExecutablesPath = _ffmpegDir;
await FFmpeg.GetLatestVersion();
```

Anything I am missing?

**Comment by tomaszzmuda** [comment]
@w0ns88 
Unfortunately, we use Zeranoe builds when user want to download Full version of FFmpeg (with gpu support).
You have to install it on your own, or use minimal ffmpeg build. You can achive that by passing "fullVersion: false" to FFmpeg.GetLatestVersion();

**Comment by ohadschn** [comment]
In the current API, that would be `FFmpegVersion.Official`

**Comment by mehmetkaradeniz** [comment]
For details see chapter "Download FFmpeg executables" at https://ffmpeg.xabe.net/docs.html
