### ISSUE TITLE
Misleading SetChannels

### ISSUE THREAD

**Issue by Vodolazz** [tomaszzmuda/Xabe.FFMpeg#2]
Hi, there's a problem with .SetChannels function when it is called with operations on video, which require encoding and decoding again.

Flag that .SetChannels set in the command line turns on stream-copy mode which is used to change video meta or container, look here: http://ffmpeg.org/ffmpeg.html#Stream-copy
When this mode is used with operations which require encoding and decoding video (scaling, changing codecs etc), ffmpeg returns error and your lib throws exception.

It will be great to give more clear naming to .SetChannels or/and also check if .setVideo/.setScale and .SetChannels are being used simultaneously to warn user from such an action.

**Comment by tomaszzmuda** [comment]
Hi.
I'm going to make check during building ffmpeg arguments, but i'm thinking about the best way to do it.

I'll do some changes to SetChannels too soon.

**Comment by tomaszzmuda** [comment]
I have done it in new version. Please update package to version 1.4.0.
