### ISSUE TITLE
Converting .webm to .mp3 doubles track length

### ISSUE THREAD

**Issue by Grahmification** [tomaszzmuda/Xabe.FFmpeg#201]
Hi,

I'm converting a .webm file to .mp3 using the following command:

Conversion.ExtractAudio("input.webm", "output.mp3").Start();

Doing so seems to double the length of the track and halve the displayed bitrate. I think the issue is that the software is incorrectly changing the duration and bitrate metadata tags; some audio players still seem to recognize the correct original values. This issue appears to be documented here:

https://superuser.com/questions/892996/ffmpeg-is-doubling-audio-length-when-extracting-from-video/893044

**Comment by 06needhamt** [comment]
Hi @Grahmification. Thanks for the report. 

As this seems to be an issue with FFmpeg itself and not our library, it may be worth filing a bug report with them [here](https://ffmpeg.org/bugreports.html).
