### ISSUE TITLE
Dot net core 2.2

### ISSUE THREAD

**Issue by DoaaNagy** [tomaszzmuda/Xabe.FFmpeg#202]
Hi,
I am using dot net core2.2. It is working fine in my local windows machine but after deployed it on Linux server I cannot call MediaInfo
FFmpeg.ExecutablesPath = Startup.GeneralConfiguration().FFMPEGConfig.FFMPEGPath; //Absolute path
var _mediaInfo = await MediaInfo.Get(Absolute File path);
It gave me this error :
Not a directory.

Thanks in advance.

**Comment by tomaszzmuda** [comment]
Hello @DoaaNagy 
Can you send the value of FFmpeg.ExecutablesPath? It should be a directory, not path to ffmpeg executable file.
