### ISSUE TITLE
JSON parse error in MediaInfo.Get

### ISSUE THREAD

**Issue by Setsu-BHMT** [tomaszzmuda/Xabe.FFmpeg#204]
A call to MediaInfo.Get will fail if certain unicode characters (such as "檔") is included in the path. For example, the path "C:\檔\Video.mp4" will fail with the error: Bad JSON escape sequence: \V. Path 'format.filename'

**Comment by tomaszzmuda** [comment]
Hello @Setsu-BHMT 
We need more info to solve this problem.
https://github.com/tomaszzmuda/Xabe.FFmpeg/pull/205
I added a test to check that and it seems that everything works fine.
Can you provide us details about your operating system and localization settings?

**Comment by Setsu-BHMT** [comment]
Absolutely!
After some further testing I've found that it needs to be called asynchronously for the bug to trigger:
`private async void Method()
{
    var mediaInfo = await MediaInfo.Get(pathWithOffendingChar);
}`

Version of Xabe is 3.5.0 and Newtonsoft.Json is 12.0.3
OS: Windows 10 Pro x64 build 19041.1
Localization: English (US)

**Comment by tomaszzmuda** [comment]
Still cannot reproduce it ;/
I've found possible case. Can you write down result from this command?
ffprobe.exe -v quiet -print_format json -show_format C:\檔\Video.mp4

In my PC looks like this (檔 symbol is shown as ?):
![image](https://user-images.githubusercontent.com/13612984/70861986-5a2fd280-1f36-11ea-91a2-f3dfe80e97e1.png)

**Comment by Setsu-BHMT** [comment]
> {
>     "format": {
>         "filename": "螟ｧ讙疲｡・\Video 100.mp4",
>         "nb_streams": 2,
>         "nb_programs": 0,
>         "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
>         "format_long_name": "QuickTime / MOV",
>         "start_time": "0.000000",
>         "duration": "37077.071000",
>         "size": "13220905876",
>         "bit_rate": "2852632",
>         "probe_score": 100,
>         "tags": {
>             "major_brand": "isom",
>             "minor_version": "512",
>             "compatible_brands": "isomiso2avc1mp41",
>             "creation_time": "1970-01-01T00:00:00.000000Z",
>             "encoder": "Lavf52.64.2"
>         }
>     }
> }

Is what I got with that command. This directory was created on a local machine (no other OS), and it doesn't matter where it lives (C:\ D:\ or network drive)

**Comment by tomaszzmuda** [comment]
It's problem of FFmpeg itself.
Look at this link:
https://trac.ffmpeg.org/ticket/2502

But I found how this problem can be solved! Probably tomorrow I will release version 3.5.1 with fix :)

**Comment by tomaszzmuda** [comment]
#207

**Comment by Setsu-BHMT** [comment]
Confirmed bug is fixed :D
