### ISSUE TITLE
[Question] How to convert mp3 content already in memory to wav

### ISSUE THREAD

**Issue by JieZou1** [tomaszzmuda/Xabe.FFmpeg#206]
We are very new to Xabe and experimenting Xabe for doing some conversion from MP3 to WAV. I use the Conversion.ExtractAudio() function, and it seems that the conversion itself works perfectly. Basically, the most important line of code for the conversion is:

              Conversion.ExtractAudio(file_mp3, file_wav).Start().Wait();

However, this function accepts only files as the input and the output. We are implementing a Web service, and the goal is to convert short (a few seconds) mp3 audios to WAV on the fly. So, the input mp3 content is a binary payload to the service request. The speed of our web service is critical, so, saving and reading mp3 and wav from files (even into memory disk) are not an option. 

Do you have any suggestions that we could do the conversion in memory? Many thanks indeed.

**Comment by tomaszzmuda** [comment]
Hello @JieZou1 
As I know it's possible to achieve that using the FFmpeg but it will require a lot of work.
https://stackoverflow.com/questions/5237175/process-video-stream-from-memory-buffer
Look at this solution. It's written in C/C++ so it would be hard to move this solution to C#. 
Right now you don't plan to add support for this. but we can help you if you want to contribute.

**Comment by JieZou1** [comment]
@tomaszzmuda, many thanks for your quick reply. Do you have any idea how much the performance (speed) gain that we could potentially achieve by switching from NAudio to ffmpeg? Many thanks.

**Comment by tomaszzmuda** [comment]
I can't find any comparison or estimations. You have to check. 
It would be great if you share results here :)
