### ISSUE TITLE
OnProgress totalLength parameter doesn't respect In and Out points

### ISSUE THREAD

**Issue by rastographics** [tomaszzmuda/Xabe.FFmpeg#21]
The `totalLength` parameter that gets passed to the OnProgress event handler gives the total length of the input file (which can then be used to calculate the % of progress completed).

However, when passing an "In" or "Out" point to ffmpeg (using `-ss` and `-t` ffmpeg arguments), the `totalLength` parameter still gives the length of entire video clip. This throws off the calculations of % of progress completed.

Is there a particular reason why the `totalDuration` doesn't account for the `-ss` or `-t` arguments? And if so, can the OnProgress event handler be given a third parameter like `segmentLength` or similar, that respects the `t` and `ss`?

I can help with a Pull Request if you are open to accepting it.

**Comment by tomaszzmuda** [comment]
It's a bug.
I haven't tought about it.
I don't know if this will be easy to implement but if you want I'll be glad to accept your pull request :)

I suppose whole method of calculating lenght should be refactored. Now it using totalDuration of input video. You can calculate this duration from -t and -ss arguments.

But this have to be done soon.
I'll do this in few days anyway.

**Comment by tomaszzmuda** [comment]
I have fix this bug.
[Commit link](https://github.com/tomaszzmuda/Xabe.FFmpeg/commit/26429795355270d82e065047589eae3a05565ef8)
Please, tell me if this solve your problem.
I've tested it but maybe you have some specific situation.
This will be avaiable from version 2.2.0, which should be released in few days. Everything is in repo yet.

**Comment by rastographics** [comment]
thanks I havent had chance to test yet but I will let you know.
