### ISSUE TITLE
Add ability to use FFmpeg Hash

### ISSUE THREAD

**Issue by jgozner** [tomaszzmuda/Xabe.FFmpeg#221]
Hi there, 

Do you plan on adding ffmpeg's hashing ability?

https://ffmpeg.org/ffmpeg-formats.html#hash-1

If not could I submit a pr for this?

**Comment by tomaszzmuda** [comment]
Hey,

It would be great if you can create a pull request :)
It's nice feature but currently we don't have capacity to implement that.
