### ISSUE TITLE
Invalid file. Cannot load file Test.pcm

### ISSUE THREAD

**Issue by bijaykush** [tomaszzmuda/Xabe.FFmpeg#222]
@AwanesowArtem, @tomaszzmuda or others who can help with this.

I am trying to convert raw pcm file into wav/mp3, but the following exceptions encounters
`Invalid file. Cannot load file Test.pcm`

While trying with FFmpeg command tools:
`ffmpeg -f s16le -ar 16k -ac 1 -i test.pcm file2.wav` it works as expected.

My code snippet for conversion:

```
private async Task RunConversionAsync(FileInfo fileToConvert)
        {
            try
            {
                string outputFileName = Path.ChangeExtension(fileToConvert.Name, ".mp3");
                var mediaInfo = await MediaInfo.Get(fileToConvert).ConfigureAwait(false);

                var audioStream = mediaInfo.AudioStreams.First();
                audioStream.ChangeBitrate(16);
                audioStream.SetSampleRate(16000);
                audioStream.SetChannels(1);

                var conversion = Conversion.New().AddStream(audioStream).SetOutput(outputFileName).SetAudioBitrate("16K");

                await conversion.Start().ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
```
Error encountered at this line in the above code
`var mediaInfo = await MediaInfo.Get(fileToConvert).ConfigureAwait(false);`

**Comment by tomaszzmuda** [comment]
It fails in FFprobe. 
Can you type this commands in your console?
`ffprobe -v quiet -print_format json -show_streams {filename}`
and later
`ffprobe -v quiet -print_format json -show_entries format=size,duration,bit_rate {filename}`
Or can you uploade this file somewhere. I'll check what's happened.

**Comment by bijaykush** [comment]
Hi @tomaszzmuda 
Thanks for the information.

I tried to run the above commands on test.pcm
1) `ffprobe -v quiet -print_format json -show_streams test.pcm`

![image](https://user-images.githubusercontent.com/11793622/73343601-f9234a80-42a8-11ea-9e22-c2af969f9d25.png)

2) `ffprobe -v quiet -print_format json -show_entries format=size,duration,bit_rate test.pcm`
![image](https://user-images.githubusercontent.com/11793622/73343672-19530980-42a9-11ea-914f-cf5a78adcf50.png)

But when I tried by converting that .pcm file into .wav by directly by using FFMPEG command:
`ffmpeg -f s16le -ar 16k -ac 1 -i test.pcm test.wav`

Ang again executing commands suggested by you on test.wav:
1.
![image](https://user-images.githubusercontent.com/11793622/73343876-6fc04800-42a9-11ea-8b85-c44bb07f63d2.png)

2. 
![image](https://user-images.githubusercontent.com/11793622/73343931-8797cc00-42a9-11ea-9d3e-1c120b8cee8c.png)


**Note**: If you need that file, Please find it [here](https://www.dropbox.com/s/qrj1qj89o8zl945/test.pcm?dl=0).

**Comment by tomaszzmuda** [comment]
It's hard to do something with this. This will change a lot of logic.
I will leave this as a feature but do not have enough time to implement this right now.

**Comment by bijaykush** [comment]
Hi @tomaszzmuda 

Thanks for your help. I tried to solve this issue by the following approach.

```
 private async Task RunConversionAsync(FileInfo fileToConvert)
        {
            try
            {
                string outputFilePath = Path.Combine(fileToConvert.DirectoryName, Path.GetFileNameWithoutExtension(fileToConvert.Name) + FileExtensions.Mp3);
                var conversion = Conversion.New();
                conversion.Clear();
                conversion.AddParameter($@"-f s16le -ar 16k -ac 1 -i {fileToConvert.FullName} {outputFilePath}");

                await conversion.Start().ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
```

I just provided the input options before the input file and added the command in the Parameter functions. It worked.
