### ISSUE TITLE
How to set Executable Path For FFmpeg on Centos 7?

### ISSUE THREAD

**Issue by erdogansonmez** [tomaszzmuda/Xabe.FFmpeg#227]
I am using .Net Core 3.1 and running on Centos 7.
I already installed FFmpeg libraries to the Centos, and i want to use already installed library.

How can i set?

**Comment by tomaszzmuda** [comment]
Hey,

Xabe.FFmpeg should get path from PATH env variable. You don't have to do anything

**Comment by erdogansonmez** [comment]
@tomaszzmuda thanks for quick reply, thats awesome!
Hava a nice day.
