### ISSUE TITLE
AudioStream.CopyStream method fails

### ISSUE THREAD

**Issue by CaffeineJunkie** [tomaszzmuda/Xabe.FFmpeg#233]
The AudioStream CopyStream method sets the parameters to -c:v copy
For audio streams this should be -c:a copy

**Comment by tomaszzmuda** [comment]
Thanks for info. I'll fix that and write some tests.
This will be available in next minor version (I guess on Wednesday)

**Comment by CaffeineJunkie** [comment]
I'm looking at the code and my initial thoughts may be wrong.  I saw -c:v copy in the stack trace and jumped to conclusions.  Certainly -c:a copy is correct, but the code is 
`_audioFilters["-c:v copy"] = string.Empty;`
This might be doing something different to what I thought.

Basically I'm trying to convert the video to H265 while leaving the audio streams intact.  I added the audiostreams to the conversion with the following:
`            foreach (IAudioStream audioStream in mediaInfo.AudioStreams)
            {

                conversion.AddStream(audioStream.CopyStream());
            }`

The conversion failed and I saw in the stack trace:
`[AVFilterGraph @ 0000024f6fea4a00] No such filter: '-c:v copy'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:1`

**Comment by tomaszzmuda** [comment]
Can you try ```conversion.AddStream(audioStream.SetCodec(AudioCodec.Copy));```
instead of ```conversion.AddStream(audioStream.CopyStream());``` ?

**Comment by CaffeineJunkie** [comment]
Thanks, that works.  

I'll close this and put it down to not understanding what CopyStream is really meant for.

**Comment by tomaszzmuda** [comment]
I think CopyStream is something remaining from previous functionality. I have to investigate what should I do with that. I'll reopen this till I deploy fix.

**Comment by CaffeineJunkie** [comment]
Just to let you know.  Yes, AudioCodec.Copy worked for me, but only because I pulled the code and compiled it.  AudioCodec.Copy and SubtitleFormat.Copy aren't in the currently released version.

**Comment by CaffeineJunkie** [comment]
Is there a reason you implemented AudioCodec.Copy in the latest version, but not SubtitleFormat.Copy?
It was in the code I pulled from Github at the time.

**Comment by tomaszzmuda** [comment]
No, I just didn't know if this is possible and needed.
You could use **new SubtitleFormat("copy")** right now to achieve that.

**Comment by CaffeineJunkie** [comment]
new SubtitleFormat("copy") does not work. 
[NULL @ 000001f929c65020] Requested output format 'copy' is not a suitable output format
nor does new SubtitleFormat("Copy") 
[NULL @ 000001f929c65020] Requested output format 'Copy' is not a suitable output format

I'll go back to my self compiled version that contains SubtitleFormat.Copy for now.

**Comment by 06needhamt** [comment]
@tomaszzmuda @CaffeineJunkie Is this issue still relevant in the current version? I can't see where the user can set the SubtitleFormat anymore?

**Comment by CaffeineJunkie** [comment]
I'm still using an old version from github that allows the following:
`conversion.AddStream(subtitleStream.SetFormat(SubtitleFormat.Copy))`

My use case is that my code reencodes my library in H265, but I want to keep audio and subtitle streams intact.
