### ISSUE TITLE
NullReferenceException when using downloader in 3.6.0

### ISSUE THREAD

**Issue by shravan2x** [tomaszzmuda/Xabe.FFmpeg#239]
Using `FFmpeg.GetLatestVersion()` or `FFmpeg.GetLatestVersion(FFmpegVersion.Full)` throws an NRE:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xabe.FFmpeg.Downloader.FFmpegDownloaderBase.get_OperatingSystem()
   at Xabe.FFmpeg.Downloader.FFmpegDownloaderBase.get_FfmpegDestinationPath()
   at Xabe.FFmpeg.Downloader.FFmpegDownloaderBase.CheckIfFilesExist()
   at Xabe.FFmpeg.Downloader.Zeranoe.FullFFmpegDownloader.GetLatestVersion()
   at Xyz.MyProject.Method()
```

This seems to be because the downloaders aren't passed in an `IOperatingSystemProvider` when they're being initialized at https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/4cdb724417634f393f291adf5afcaa3c07d84d89/Xabe.FFmpeg/FFmpeg.cs#L89

So they are set to null by default at
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/752fb08e49d423d36c136be0be22c8f3a50f6137/Xabe.FFmpeg/Downloader/Official/FFmpegDownloader.cs#L13

So calling the `OperatingSystem` getter throws an NRE at
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/752fb08e49d423d36c136be0be22c8f3a50f6137/Xabe.FFmpeg/Downloader/FFMpegDownloaderBase.cs#L13

The tests don't catch this issue since they explicitly pass in an `IOperatingSystemProvider`
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/752fb08e49d423d36c136be0be22c8f3a50f6137/Xabe.FFmpeg.Test/DownloaderTests.cs#L25

**Comment by tomaszzmuda** [comment]
Thanks for fix!
It will be pushed to NuGet in a few minutes.

**Comment by Almeonamy** [comment]
I continue to get the NullReferenceException on FFmpeg.GetLatestVersion in version 3.6.1

**Comment by tomaszzmuda** [comment]
I add test for that and push fix to NuGet today.

**Comment by tomaszzmuda** [comment]
Fix pushed to NuGet
