### ISSUE TITLE
Subtitles...

### ISSUE THREAD

**Issue by alex6dj** [tomaszzmuda/Xabe.FFmpeg#24]
Ability to add subtitles as a new stream for mkv or others, as well as embedded within the video itself permanently.

**Comment by tomaszzmuda** [comment]
Done!
[Adding subtitles](https://github.com/tomaszzmuda/Xabe.FFmpeg/wiki/Adding-subtitles)
Please tell me if it works in your case.
I have tested it but maybe in different case.
You have to update Xabe.FFmpeg to 2.2.1

**Comment by alex6dj** [comment]
Ok, I already looked at the code and both options should work fine.

I have not tried it yet because I do not have internet in the place that I program (my house) and I have to go for the tests but it should work.

Another thing in the case of Burning subtitles. Give some option to manually or automatically put the subtitle encoding (UTF-8, ANSI, etc), because from experience I know that ffmpeg does not detect it and you can end up with a video showing a lot of Chinese characters that is not what is wanted.

To detect it I use

[https://github.com/errepi/ude](url)

And so far I have not failed ...

I convert daily more than 400 videos automatically and about 50 of them come with subtitles (.srt).

Thanks for all your work, because I am a novice programmer and I do not think I can do a job like this ...
