### ISSUE TITLE
Problems with operating system culture

### ISSUE THREAD

**Issue by SimonSchoeni** [tomaszzmuda/Xabe.FFmpeg#244]
Hi!

I'm using Xabe.FFmpeg in an ASP.NET application used in Electron.NET. 
While testing I found that I constantly get exceptions while on an OS with german speech settings. 
The output of FFmpeg was the following:
`Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[libmp3lame @ 0000024614707e40] [Eval @ 000000bcbe9fe1f0] Invalid chars ',999K' at the end of expression '95,999K'
[libmp3lame @ 0000024614707e40] Unable to parse option value "95,999K"
[libmp3lame @ 0000024614707e40] Error setting option b to value 95,999K.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`

As you can see, the wrapper passes 95,999k towards FFmpeg. 
The whole problem is the decimal seperator. German operating systems use comma (,)  as decimal seperator whereas english and other operating systems use dot (.) as decimal seperator.
It seems, that FFmpeg only accepts dot as decimal seperator, therefore the wrapper should be able to always convert culture dependent decimal seperator of the os to the english version before calling FFmpeg.
Currently the only workaround to this problem is to switch the culture of the operating system to english...

**Comment by tomaszzmuda** [comment]
Hi @SimonSchoeni
Thanks for feedback! I'm going to resolve this issue as fast as possible.
I will let you know when the fix will be on NuGet.

**Comment by SimonSchoeni** [comment]
Hey @tomaszzmuda !
Thank you for the quick reply! 
Looking forward to it :) 
besides that the wrapper seems to be really good work! 
Thank you for that!

**Comment by tomaszzmuda** [comment]
Changes are on PR #245 but it will break the previous API. It will be available in the next major version.
I think I'll prepare it till the end of the weekend.

**Comment by SimonSchoeni** [comment]
@tomaszzmuda Do you know, when the next major version will be released on NuGet?

**Comment by tomaszzmuda** [comment]
Probably on Monday. There are some other things that I need to change but I did not break the contract. Right now you could pass bitrate as a string but without decimal place:
e.g. "92999" instead of "92.999k" and it should works :)

**Comment by SimonSchoeni** [comment]
Ok, thank you very much for the quick fix! :) Would you mind letting me know once it is released on NuGet? :)

**Comment by tomaszzmuda** [comment]
Of course!

**Comment by tomaszzmuda** [comment]
Hey @SimonSchoeni 
I have released version 4-beta on NuGet. It will take me much more time than I thought.
Right now feel free to use beta version :)

**Comment by SimonSchoeni** [comment]
@tomaszzmuda Hey! :)
Thank you very much for your efforts - i will use the beta asap :)
I just viewed your changes in the PR. I saw that you changed the type to long instead of double. I do not have insight in your code and how you actually pass the bitrate to ffmpeg - so please correct me if I'm wrong: I guess at some point you have the convert the bitrate double into a string... If that ia the case, you could have used something like a NumberFormatInfo, which applies to dot net core and standard. Please don't get me wrong, this was just a simple solution that would not result in you breaking interfaces. :)

Br
Simon

**Comment by tomaszzmuda** [comment]
Hey,

You are right :)
But bitrate was a string somewhere and double in other places. The methods to set bitrate were named differently too. I wanted to unify this from a long time but was too busy for that.

**Comment by SimonSchoeni** [comment]
Oh, I see :) 
It's always good to have an issue as reason to perform a long planned refactoring 😜

**Comment by tomaszzmuda** [comment]
Everything was deployed as stable version 4.0.0
It took me a little longer than I expect. 
I hope I resolved this problem for good.

**Comment by SimonSchoeni** [comment]
@tomaszzmuda Hi!
I integration tested it and it seems to work nicely :) Thank you again for the quick fix! I will close the issue for good
