### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by EricNjue** [tomaszzmuda/Xabe.FFmpeg#246]
Hello, I'm experiencing the above issue when running xabe in a docker container on ubuntu.

> Exec format error -> at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
> at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
> at System.Diagnostics.Process.Start()
> at Xabe.FFmpeg.FFmpeg.RunProcess(String args, String processPath, Nullable`1 priority, Boolean standardInput, Boolean standardOutput, Boolean standardError)
> at Xabe.FFmpeg.FFprobeWrapper.<>c__DisplayClass8_0.<RunProcess>b__0()
> at System.Threading.Tasks.Task`1.InnerInvoke()
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
> at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location where exception was thrown ---
> at Xabe.FFmpeg.FFprobeWrapper.GetStream(String videoPath)
> at Xabe.FFmpeg.FFprobeWrapper.GetProperties(FileInfo fileInfo, MediaInfo mediaInfo)

How can this be resolved?

**Comment by tomaszzmuda** [comment]
Hi @EricNjue 
Tell me please from where do you get FFmpeg executables?
You run this container on Windows?

**Comment by EricNjue** [comment]
Hi @tomaszzmuda 

The executables are in the ubuntu machine.

I'm running the container on Linux.

**Comment by tomaszzmuda** [comment]
![image](https://user-images.githubusercontent.com/13612984/78938111-f23b6400-7ab1-11ea-9b90-b5ba8c7fa446.png)
I tried it on mcr.microsoft.com/dotnet/core/sdk:3.1. Run Example project with changed path to images. (I had to add permission to downloaded files.
It seems like you have wrong/corrupted FFmpeg binaries. Can you upload them here? Or provide some more info

**Comment by EricNjue** [comment]
Here's the link for the binaries am using.
https://drive.google.com/file/d/1wcIzcJq0BQ5v9T7QCLOBgkv9YjxVvRjH/view?usp=sharing

**Comment by tomaszzmuda** [comment]
These binaries are prepared for Windows. It does not work on Linux. You have to download binaries for Linux. You can use FFmpeg.GetLatestVersion() - it will download all binaries for your operating system (there is a problem with permissions so maybe you will have to manually add +x permission). 
The best way to do that in this moment is by installing FFmpeg during the creation of docker image.

**Comment by EricNjue** [comment]
If I use FFmpeg.GetLatestVersion() without installing ffmpeg during Creation of docker image will it work?

**Comment by tomaszzmuda** [comment]
Yes, but sometimes it does not have executable permission. Look at this #200

**Comment by EricNjue** [comment]
Alright then. Thank you @tomaszzmuda. Let me do that then revert.

**Comment by EricNjue** [comment]
This can now be closed. It has worked. @tomaszzmuda  thank you for the insights.
