### ISSUE TITLE
[Question] How to parse every frame of video ?

### ISSUE THREAD

**Issue by Nonobis** [tomaszzmuda/Xabe.FFmpeg#247]
Hello,
I am trying to do a foreach on each frames of a video stream, check content of frame for a particuliar image (with a simularity %) and extract timestamp of frame ?
Can i do this with this library ?

Thanks :)

**Comment by tomaszzmuda** [comment]
Hey @Nonobis,

In my opinion, the easiest way is to use ExtractEveryNthFrame(1, .....) and check this content on output files :)

Link to documentation: [Video <-> Image conversion](https://ffmpeg.xabe.net/docs.html)

**Comment by Nonobis** [comment]
Thanks, will try it ... i really simple to extracte frame...
how can i extrapoling timestamp corresponding to extracted frame with this ?

**Comment by tomaszzmuda** [comment]
I don't know what precise do you need but you can calculate this.
You can get framerate so calculating time is not a problem.
E.g.
If the video has framerate 30, when you get 31 frame it's time is equal 1.03s.
Convert.ToInt32(31 / framerate) + ((31 % framerate) / framerate) - it's just a draft

**Comment by Nonobis** [comment]
Thanks a lot :)
