### ISSUE TITLE
Every conversion in conversion queue is throwing an exception

### ISSUE THREAD

**Issue by sweeneypng** [tomaszzmuda/Xabe.FFmpeg#248]
When creating a ConversionQueue, the following code runs in the constructor:
```
    for (var i = 0; i < (_parallel && Environment.ProcessorCount > 1 ? Environment.ProcessorCount : 1); i++)
    {
        var task = Task.Factory.StartNew(() => CreateWorkerTaskAsync(_cancellationTokenSource.Token), _cancellationTokenSource.Token, TaskCreationOptions.LongRunning, TaskScheduler.Default);
        _tasks.Add(task);
    }
```
When calling the Start method on the queue, after instantiating it:
```
public void Start(CancellationTokenSource cancellationTokenSource = null)
{
     _cancellationTokenSource?.Dispose();
     _cancellationTokenSource = cancellationTokenSource ?? new CancellationTokenSource();
     _start.Set();
}
```

Disposing the CancellationTokenSource that has already been handed to the worker tasks will cause an ObjectDisposedException for every conversion in the queue. In the unit test for the queue, this scenario is being tested by throwing an exception in the event handler for OnException.

```
            queue.OnException += (number, count, conversion) =>
            {
                resetEvent.Set();
                throw new Exception();
            };
```

Exceptions are indeed thrown from the event handler when running this code. Unfortunately, they do not cause the unit test to fail. I believe this is because the exception is being thrown from a worker thread instead of the main thread for the unit test. A flag should be set from the event handler that can be tested in the main thread after waiting on the resetEvent.

**Comment by tomaszzmuda** [comment]
Helo @sweeneypng 
I will take a look on that.

**Comment by tomaszzmuda** [comment]
Hey,

Finally, I found time to look what's going on. 
You are right, every conversion thrown exception. This interface was badly designed (my bad). I'm going to rewrite it to working well :)

**Comment by tomaszzmuda** [comment]
It would be great if you can write down how do you want to use the queue.
I'm thinking about just deleting this, but maybe there are few cases (like static class gathering conversions from whole application) which it will be useful.
