### ISSUE TITLE
[v4.0.7-beta] Success property has been removed from IConversionResult

### ISSUE THREAD

**Issue by 06needhamt** [tomaszzmuda/Xabe.FFmpeg#249]
I've just finished testing all of the scenarios in my project with the v4.0.7-beta and everything seems to work as expected except for the `Success` property seems to have been removed from `IConversionResult`. Was this intended? If so what is the proper way to check if a conversion was successful in the V4 API?

**Comment by tomaszzmuda** [comment]
Hey,

I have removed **Success** property because it was always true. If something went wrong proper exception are thrown so there is no need to check this status.
Do you have any places where **Success** was set to false and you got no exception?

**Comment by 06needhamt** [comment]
Hey

I've not had any that I can think of immediately, but that makes sense that an exception would be thrown when an error occurs.

**Comment by 06needhamt** [comment]
I have done some further testing to ensure a conversion never fails without an exception and in my 1000+ test scenarios I have experienced no such behaviour so I will close the issue.
