### ISSUE TITLE
Extract subtitles

### ISSUE THREAD

**Issue by alex6dj** [tomaszzmuda/Xabe.FFmpeg#25]
Ability to extract subtitles from a video file and maybe convert from one format to another (from ass to srt)

**Comment by tomaszzmuda** [comment]
Ability to extract subtitles requires too much changes to be done soon.
I'm going to work on it but you have to wait some time (few days at least).
About convert subtitles I'll try add class to do it easily but you can use Xabe.FFmpeg.Convert class for it.

```
bool conversionResult = await new Conversion()
     .SetInput("output.ass")
     .SetOutput("input.srt")
     .Start();
```

It should work according to: [FFmpeg docs](https://trac.ffmpeg.org/wiki/HowToConvertSubtitleToASS)

**Comment by alex6dj** [comment]
ok I will test and let you know...

**Comment by lkischler** [comment]
It will work in version 3.0
