### ISSUE TITLE
Possible deadlock

### ISSUE THREAD

**Issue by leonardoangelini** [tomaszzmuda/Xabe.FFmpeg#254]
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/4083ba511d0fa51d0db01b83367679592d9ca0a2/src/Xabe.FFmpeg/FFmpeg.cs#L198

Hi, first of all thanks for the project.
I'm trying to use your ffmpeg wrapper but sometimes the process seems hang.

In this post, someone tells about a deadlock about Process class.
The Microsoft reference is https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?redirectedfrom=MSDN&view=netcore-3.1#System_Diagnostics_Process_StandardOutput

Anybody has my problem about deadlock/hanging during the process?

**Comment by tomaszzmuda** [comment]
Hey @leonardoangelini 
I cannot reproduce this issue but tried the best to fix it.
#256 - could you please try to use code from this branch in your project? If it works I will push it to NuGet.

**Comment by leonardoangelini** [comment]
Hi @tomaszzmuda, is not easy to reproduce the issue. It hardly ever occurs locally on my Mac, but it often occurs in the docker environment in a kubernetes cluster. I can try to fix it and if it works a will push the code.

**Comment by tomaszzmuda** [comment]
Code in [this branch](https://github.com/tomaszzmuda/Xabe.FFmpeg/tree/RemoveStandardOutputFromFFmpegProcess) should fix this so you can use it. 
Looking forward to hearing from you!
