### ISSUE TITLE
Error converting image to video

### ISSUE THREAD

**Issue by yesidbalvin** [tomaszzmuda/Xabe.FFmpeg#257]
We are using Xabe.FFmpeg to concatenate some images and videos into one single video ( image-video-image-video), the microservice is deployed into a Linux container using  DotNetCore 3.1(Runtime Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]), the thing is when we try to use it to convert the first image into a video we are getting this error, which as you can see is not very explicit with the proper error.

{"@t":"2020-05-19T13:36:06.1347355Z","@mt":"FFmpegMediaCombiner: Starting media convertion of: **-loop 1 -i MediaProcessor/tempMedia/c262f16b-9c73-49fe-8121-de587102da47/media_05192020133603-034.jpg -c:v libx264 -t 3 -pix_fmt yuv422p -vf \"pad = ceil(iw / 2) * 2:ceil(ih / 2) * 2\" MediaProcessor/tempVideo/c262f16b-9c73-49fe-8121-de587102da47/VID_1_05192020133606.ts**",}
{"@t":"2020-05-19T13:36:07.7116663Z","@mt":"Exception catch. Error while converting files. Exception --> {0}","@l":"Error","0":"Xabe.FFmpeg.Exceptions.ConversionException: ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 22.100 / 56. 22.100\n  libavcodec     58. 35.100 / 58. 35.100\n  libavformat    58. 20.100 / 58. 20.100\n  libavdevice    58.  5.100 / 58.  5.100\n  libavfilter     7. 40.101 /  7. 40.101\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  3.100 /  5.  3.100\n  libswresample   3.  3.100 /  3.  3.100\n  libpostproc    55.  3.100 / 55.  3.100\nInput #0, image2, from 'MediaProcessor/tempMedia/c262f16b-9c73-49fe-8121-de587102da47/media_05192020133603-034.jpg':\n  Duration: 00:00:00.04, start: 0.000000, bitrate: 6964 kb/s\n    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 720x560 [SAR 96:96 DAR 9:7], 25 fps, 25 tbr, 25 tbn, 25 tbc\nStream mapping:\n  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))\nPress [q] to stop, [?] for help\n[swscaler @ 0x55ce25653cc0] deprecated pixel format used, make sure you did set range correctly\n[libx264 @ 0x55ce24e6c1c0] using SAR=1/1\n[libx264 @ 0x55ce24e6c1c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2\n[libx264 @ 0x55ce24e6c1c0] profile High 4:2:2, level 3.0, 4:2:2 8-bit\nOutput #0, mpegts, to 'MediaProcessor/tempVideo/c262f16b-9c73-49fe-8121-de587102da47/VID_1_05192020133606.ts':\n  Metadata:\n    encoder         : Lavf58.20.100\n    Stream #0:0: Video: h264 (libx264), yuv422p, 720x560 [SAR 1:1 DAR 9:7], q=-1--1, 25 fps, 90k tbn, 25 tbc\n    Metadata:\n      encoder         : Lavc58.35.100 libx264\n    Side data:\n      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1\nframe=   43 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    \n   at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_0.<RunProcess>b__0()\n   at System.Threading.Tasks.Task`1.InnerInvoke()\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location where exception was thrown ---\n   at Xabe.FFmpeg.Conversion.Start(String parameters, CancellationToken cancellationToken)\n

The image properties are.
Extension: *.jpg
Size: 34Kb
Dimensions: 720x560
Horizontal Resolution: 96dpi
Vertical Resolution: 96dpi
Bit Depth: 24

**Comment by tomaszzmuda** [comment]
Hey,
I tried to run this command, and only difference between my output and yours is last line:
**frame= 43 fps=0.0 q=0.0 size= 0kB time=00:00:00.00 bitrate=N/A speed= 0x**
vs
**frame=   75 fps=0.0 q=-1.0 Lsize=      16kB time=00:00:02.88 bitrate=  44.4kbits/s speed=10.3x
**
Can you try it on different image? Is getting MediaInfo about this image works correctly?
Maybe there are additional information in InnerException.
