### ISSUE TITLE
await FFmpeg.GetMediaInfo and... Nothing

### ISSUE THREAD

**Issue by nicolascarre** [tomaszzmuda/Xabe.FFmpeg#260]
Hi,
I want to extract some frame from a video.

I do same thing of your code from here : [https://ffmpeg.xabe.net/docs.html](url)
(very last paragraph)

Here is my code :
IMediaInfo info = await FFmpeg.GetMediaInfo(Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "\\aaa.mp4");
Debug.Log("Call !!!");
IVideoStream videoStream = info.VideoStreams.First()?.SetCodec(VideoCodec.png);

and never The Debug.Log is called.

Please can you help me

**Comment by tomaszzmuda** [comment]
Hey,
Do you get any exceptions? Can you do it inside try catch block with catching all Exceptions?

**Comment by nicolascarre** [comment]
There is no exception, but it is catch when I put the code in a try catch

**Comment by nicolascarre** [comment]
Actualy I have this exception :

"Xabe.FFmpeg.Exceptions.FFmpegNotFoundException: Cannot find FFmpeg in PATH. This package needs installed FFmpeg. Please add it to your PATH variable or specify path to DIRECTORY with FFmpeg executables in FFmpeg.ExecutablesPath\r\n  at Xabe.FFmpeg.FFmpeg.ValidateExecutables () [0x00053] in <89450411a37144bd98a7ec27637fe9b9>:0 \r\n  at Xabe.FFmpeg.FFmpeg.FindAndValidateExecutables () [0x00129] in <89450411a37144bd98a7ec27637fe9b9>:0 \r\n  at Xabe.FFmpeg.FFmpeg..ctor () [0x00006] in <89450411a37144bd98a7ec27637fe9b9>:0 \r\n  at Xabe.FFmpeg.FFprobeWrapper..ctor () [0x00000] in <89450411a37144bd98a7ec27637fe9b9>:0 \r\n  at Xabe.FFmpeg.MediaInfo+<Get>d__27.MoveNext () [0x00016] in <89450411a37144bd98a7ec27637fe9b9>:0 \r\n--- End of stack trace from previous location where exception was thrown ---\r\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at Xabe.FFmpeg.MediaInfo+<Get>d__26.MoveNext () [0x0007a] in <89450411a37144bd98a7ec27637fe9b9>:0 \r\n--- End of stack trace from previous location where exception was thrown ---\r\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at Xabe.FFmpeg.FFmpeg+<GetMediaInfo>d__23.MoveNext () [0x00060] in <89450411a37144bd98a7ec27637fe9b9>:0 \r\n--- End of stack trace from previous location where exception was thrown ---\r\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 \r\n  at Nuget+<FiletoAsync>d__2.MoveNext () [0x0003f] in C:\\Users\\YamiSatie\\Desktop\\Nuget sans Nuget\\Assets\\Nuget.cs:31 "

**Comment by tomaszzmuda** [comment]
You have to use FFmpeg.SetExecutablesPath("C:/ffmpegDir") and pass the path to FFmpeg executables dir.
Without try catch you still should have exception written somewhere. In the worst case you do not handle it and you application crashes

**Comment by nicolascarre** [comment]
I have this : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ffmpegDir'.
And what do you mean by "pass the path to FFmpeg executables dir.", I don't have a FFmpeg.exe or something ?

**Comment by nicolascarre** [comment]
I found a solution, thanks
