### ISSUE TITLE
Possibilty to create IMediaInfo in memory

### ISSUE THREAD

**Issue by black-byte** [tomaszzmuda/Xabe.FFmpeg#263]
Hi Tomasz,

I've got a question whether is there some better way / are there plans for creating
IMediaInfo fully in memory. In my case, I do have all the basic information like width/height/fps for my h264/h265 video data so I would like to have IMediaInfo simply without need to invoke FFProbe.

Additionaly are there any plans for operation directly on MemoryStream. 
Why is there always need to operate on file paths instead of directly using memory stream in cases when we have from some reason the video already in memory?

Anyway, Xabe.FFmpeg looks quite awesome, well done 👍.

**Comment by tomaszzmuda** [comment]
Hey,

Unfortunately, there is no possibility to do that.
To be able to do complicated conversion with different parameters even basic conversion map streams from IMediaInfo.

`-i "multipleStreamSample.mkv" -n -threads 12 -map 0:0 -map 0:1 -map 0:8 "tempOutput.mp4"`

This code is generated when you try to convert file MultipleStreamSample.mkv located in repository. This file has 10 streams, but only 3 of them are video/audio streams. So to create IMediaInfo in memory you will have to know exact index of each stream you want to convert and it's type.

You can check streams count using `ffprobe -v panic -print_format json -show_streams .\multipleStreamSample.mkv`
