### ISSUE TITLE
Unable to create Subtitle Stream without using FFprobe

### ISSUE THREAD

**Issue by black-byte** [tomaszzmuda/Xabe.FFmpeg#266]
I've got a scenario when I'm creating in memory subtitles stream so I know every property which should be set. I don't need at all FFprobe, it's simply waste of time and resources to run it.

We should provide ability to create streams in memory with all properties.
Maybe some builder for that?

Additionally, when I'm using SetLanguage it only stores the value in private property, the Language property is original from FFprobe and I'm unable to override it / access my changed value.

**Comment by tomaszzmuda** [comment]
Hello @black-byte,

Right now support for subtitles is limited. We could extend it of course or accept PullRequest with changes. 

Can you describe whole process? I assume that you have file with subtitles and you want to just pass to FFmpeg path to this file with language you set up. Is it correct?

According to Language property: will it be enough if this field will have public getter?
