### ISSUE TITLE
Adding thumbnail

### ISSUE THREAD

**Issue by pekspro** [tomaszzmuda/Xabe.FFmpeg#271]
The [ffmpeg Documentation](https://www.ffmpeg.org/ffmpeg.html#toc-Main-options) says:

    To add an embedded cover/thumbnail:
        ffmpeg -i in.mp4 -i IMAGE -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic out.mp4
    Not all muxers support embedded thumbnails, and those who do, only support a few formats, like JPEG or PNG.

Is this supported by this libary?

**Comment by tomaszzmuda** [comment]
If you want to add picture as overlay you can use method SetWatermark (check documentation how to use it).
