### ISSUE TITLE
Create screenshot from video with external or embedded subtitle

### ISSUE THREAD

**Issue by Sonic3R** [tomaszzmuda/Xabe.FFmpeg#278]
Hi, 

I saw that `Snapshot` method has way to create screenshot of video of some time.

There is a way to capture screen from video which has embedded or external subtitle ( I want to see screen of video with visible subtitle ) ?

**Comment by tomaszzmuda** [comment]
Hello,

You could try use SetSeek on IConversion with AddParameter("-frames 1").

**Comment by Sonic3R** [comment]
I tried

```
      int ratio = (videoLengthSeconds / numScreens) - (2 * numScreens);

      string filename = Path.GetFileName(pathToVideoFile);
      int percent = 100 / numScreens;

      for (var i = 1; i <= numScreens; i++)
      {
        string screenName = Path.Combine(Path.GetDirectoryName(pathToVideoFile), $"{filename}_{i}.png");

        IConversion conv = await FFmpeg.Conversions.FromSnippet.Snapshot(pathToVideoFile, screenName, TimeSpan.FromSeconds(i * ratio));
        if (captureWithSub)
        {
          conv.SetSeek(TimeSpan.FromSeconds(i * ratio)).AddParameter("-frames 1");
        }

        IConversionResult conversionResult = await conv.Start();
        Console.WriteLine($"Status: {percent * i}%");
```

I tried to generate a `numScreens` number of screens of a video

The issue is it at SetSeek( ... do not know what value should be here ).AddArgument("-frames 1")

I tested with `SetSeek(TimeSpan.FromSeconds(i * ratio))` and seems that that a very long time and never finish

What should put there in SetSeek method ?

**Comment by tomaszzmuda** [comment]
Snapshot only takes video stream.
To do that you will have to burn subtitles previously (it will take some time) or pass your own arguments.

**Comment by Sonic3R** [comment]
I succeeded to do like:

`ffmpeg -ss 00:09:18 -copyts -i somemovie.mkv -vf subtitles=subtitle.srt -vframes 1 screenshot.png`

How can use above custom arguments using your library ?

**Comment by Sonic3R** [comment]
Ok, I solved with external subtitle, but for already burnt subtitles, how can achieve ? 

Assume that mkv has 4 subtitles (English, French, Dutch and Romanian). How can pass for `Romanian` subtitle (which is already burnt) ?

**Comment by tomaszzmuda** [comment]
I assume that "burnt" subtitles are already burnt on the video stream. You cannot separate them and every snapshot will contain these subtitles.

**Comment by Sonic3R** [comment]
I made it: first I extracted subtitle I need by reading mkv file with media info in order to know the stream index.

```
var mi = await FFmpeg.GetMediaInfo(pathToVideoFile);
var sub = mi.SubtitleStreams?.FirstOrDefault(s => s?.Language?.Equals(lang, StringComparison.OrdinalIgnoreCase) == true);
var parent = Path.GetDirectoryName(pathToVideoFile);

var subFile = Directory.GetFiles(parent, "*.srt").FirstOrDefault();

if(sub != null && subFile == null) {
  subFile = Path.Combine(parent, $"000 - {sub.Index} - Subtitle, {sub.Language}.srt");
  IConversion conv = FFmpeg.Conversions.New()
                              .AddParameter($"-i \"{pathToVideoFile}\"")
                              .AddParameter($"-map 0:{sub.Index} \"{subFile}\"");

   await conv.Start();
}
```
and then create screen capture:

```
var encode = "ISO-8859-2";
var screenName = Path.Combine(parent, "screen.png");
conv = FFmpeg.Conversions.New()
                      .AddParameter($"-ss {ts.TotalSeconds}", ParameterPosition.PreInput)
                      .AddParameter($"-copyts", ParameterPosition.PreInput)
                      .AddParameter($"-i \"{pathToVideoFile}\"")
                      .AddParameter($"-filter_complex \"subtitles='{subFile.Replace('\\', '/').Replace(":", "\\:")}':charenc={encode}\"")
                      .AddParameter($"-vframes 1 \"{screenName}\"");

await conv.Start();
```
