### ISSUE TITLE
How to add -movflags +faststart when converting .h264 files to .mp4?

### ISSUE THREAD

**Issue by younganakin** [tomaszzmuda/Xabe.FFmpeg#28]
Hi tomaszzmuda,

Is there a way to add the -movflags +faststart as an output option when converting for files that will be loaded on the browser?

**Comment by tomaszzmuda** [comment]
You can create new Conversion object and set input and output.
Next Build method will return all parameters passed to ffmpeg.
Last argument has to be output so if you split this text by space you can put all additional parameters before output. I have to add additional method to IConversion that allows user to pass arguments directly before output.  If you want, you can make PR with it. It should speed up this.

**Comment by alex6dj** [comment]
You can now put your own parameters like this:

```
bool conversionResult = await new Conversion().SetInput(Resources.MkvWithAudio)
  .AddParameter("-movflags")
  .AddParameter("+faststart")
  .SetOutput(outputPath)
  .Start();
```
Check the [Wiki](https://github.com/tomaszzmuda/Xabe.FFmpeg/wiki#own-arguments)
