### ISSUE TITLE
Downloader - support IProgress

### ISSUE THREAD

**Issue by ohadschn** [tomaszzmuda/Xabe.FFmpeg#280]
Thank you for the downloader, it works great!

It would be a nice touch to have [IProgress](https://docs.microsoft.com/en-us/dotnet/api/system.iprogress-1?view=netcore-3.1) support for the FFMpeg download though, you could use something like this: https://stackoverflow.com/a/46497896/67824.

**Comment by tomaszzmuda** [comment]
I'm going to release new version with IProgress support on Monday
