### ISSUE TITLE
mp4 to m3u8

### ISSUE THREAD

**Issue by MajidSafari** [tomaszzmuda/Xabe.FFmpeg#288]
hi , tanx for Xabe.FFmpeg

so , how can i mp4 to m3u8 play list

**Comment by tomaszzmuda** [comment]
Hey,

More more complicated params when you know the exact FFmpeg command you can use Conversion.Start(string) method.
["ffmpeg -i big.mp4 -b:v 1M -g 60 -hls_time 2 -hls_list_size 0 -hls_segment_size 500000 output.m3u8"
](https://stackoverflow.com/questions/42026691/ffmpeg-creating-m3u8-from-mp4-video-file-size)This should create m3u8 stream
