### ISSUE TITLE
Downloader - add retries

### ISSUE THREAD

**Issue by ohadschn** [tomaszzmuda/Xabe.FFmpeg#290]
I've ran into cases where intermittent network failures cause ffmpeg downloads to fail. This can be significantly remedied by retries (e.g. using https://github.com/App-vNext/Polly). 

This would be similar to how the Azure SDKs include retries (on transient failures) for all network operations - including blob uploads and downloads which are conceptually similar to the ffmpeg downloader.

**Comment by tomaszzmuda** [comment]
Hey,
Good point. I'm going to add this when I will have some free time.
Polly is not the best idea because of additional dependency. What we need is just simple do while with some tries.

**Comment by ohadschn** [comment]
Thank you for considering!

`do` / `while` with some tries would be great, but keep in mind that exponential backoff would be ideal - it's pretty easy to roll your own if you don't want to take a dependency on _Polly_ (or you could just copy their relevant code).
