### ISSUE TITLE
Way to capture in memory the frame being converted?

### ISSUE THREAD

**Issue by RejectKid** [tomaszzmuda/Xabe.FFmpeg#291]
2 part question.

I'm looking to point to a udp url and I'd like to grab the bitmap/image/frame while its converting.  It seems most things in this lib relate to using a file and the the OnProgress and OnDataReceived dont seem to have the image data in them

1) is this possible
2) how would you do this?

**Comment by tomaszzmuda** [comment]
It cannot be done right now. You can achieve that using named pipelines and listen in second app. But I will really appreciate if you share your solutions and/or create PR :)
