### ISSUE TITLE
Concatenate() video output settings do not match input settings

### ISSUE THREAD

**Issue by forReason** [tomaszzmuda/Xabe.FFmpeg#295]
Issue:
When using the following concatenate function, the output video is different from input video:
```C#
public void ConcatenateVideos(string outputPath, params string[] inputVideos)
{
    IConversion conversion = FFmpeg.Conversions.FromSnippet.Concatenate(outputPath, inputVideos).Result;
    var res = conversion.Start().Result;
}
```

What do I expect:
My output video has same format, bitrate, audiochannels as the input videos.

What is happening:
My input videos are all the same format. They have 1 videostream and two audio channels:
- 1 Stereo channel for System / Ambient Audio 
- 1 Stereo Channel for Recorded Microphone
- Possible further stereo Channels for further microphones

Additionally the input videos are little compressed only. The main reason is that I will edit the Videos later on manually in an External Video Editor (eg. Adobe premiere)

Therefore I want to have the Videos stitched together. But the quality should not change, and especially, the Audio channels should stay separated rather than merged. Otherwise I cannot master the Audio later on.

But In fact, the concatenated video is half the sitze of one of 2 input videos. Its very compressed.
![image](https://user-images.githubusercontent.com/12736950/93711638-1bc3e580-fb50-11ea-861b-646e3120aa8a.png)

The audio channels got merged or the second channel discarded. I cannot master the audio anymore.
The below Picture demonstrates this. Left is the original input file with 2 Stereo Audio streams. to the right is the concatenated file, 2nd audio stream just got discarded:
![image](https://user-images.githubusercontent.com/12736950/93740765-6e061480-fbeb-11ea-878b-c4ca6c3a178a.png)

**Comment by forReason** [comment]
I have made some Progress.

In order to actually use all Audio strems, one has to specify argument "-map 0" such as:

``` CMD
ffmpeg -f concat -i list.txt -map 0 -c:a copy -c:v copy demuxed.mp4
```

However, this does not help me much with Xabe.ffmpeg. Is there a way I can pass the map argument?

**Comment by forReason** [comment]
I have "resolved" the issue the following way:
``` C#
public void ConcatenateVideosTest(string outputPath, params string[] inputVideos)
        {
            Conversion convers = new Conversion();
            
            string textfilePath = "concat.txt";
            if (File.Exists(textfilePath)) File.Delete(textfilePath);
            StringBuilder inputList = new StringBuilder();
            foreach (string file in inputVideos)
            {
                inputList.Append("file '");
                inputList.Append(file);
                inputList.AppendLine("'");
            }
            File.WriteAllText("concat.txt",inputList.ToString());
            IConversionResult res = convers.Start("-f concat -i "+textfilePath+" -map 0 -c:a copy -c:v copy demuxed.mp4").Result;
            File.Delete(textfilePath);
        }
```

can be closed

**Comment by 06needhamt** [comment]
@forReason Thanks for the solution.
 @tomaszzmuda should we change the implementation of the concatenate snippet in the library to be something similar?
I would be happy to do the work if you are OK with it.
