### ISSUE TITLE
Downloader - use package managers and/or their links

### ISSUE THREAD

**Issue by ohadschn** [tomaszzmuda/Xabe.FFmpeg#296]
I saw that the zeranoe links died, and were [graciously replaced](https://github.com/tomaszzmuda/Xabe.FFmpeg/pull/286) with self-hosted https://xabe.net links - thank you!

Unfortunately one day even xabe.net might be down too - temporarily of course :) Which is why I propose utilizing package managers (or at least their drops) drops, which are less likely to be down/slow and more likely to be up to date. As a bonus, you'll save traffic costs and the hassle of updating ffmpeg versions.

Somewhat ironically, I believe Windows would be the easiest to implement via the [chocolatey package](https://chocolatey.org/packages/ffmpeg) - simply download this [direct link](https://chocolatey.org/api/v2/package/ffmpeg) and you get the x86 & x64 static versions.

On mac/linux a direct download approach might be more difficult (due to dependencies), but I think you should just execute the distro's package manager. So maybe support a few popular ones (`apt-get`, `yum`, `homebrew`) and if they are available execute them.

I realize this won't cover every possible scenario (e.g. esoteric Linux distros or mac machines without homebrew), but IMHO it will cover the vast majority of cases in a way that is more future proof than the current implementation.

I think a fallback approach would be ideal, where a package manager download is attempted first, and if unavailable (e.g. package managers are not installed, or package does not include requested `FFmpegVersion` flavor), fall back to one of the well-known links.

**Comment by tomaszzmuda** [comment]
Hey,

Right now the packages are self-hosted but it's a temporary solution.
I'm going to just redirect users to another source (it will be invisible for everyone).
I uploaded all builds from Zeranoe to GitHub as a release https://github.com/tomaszzmuda/Xabe.FFmpeg/releases/tag/executables
and all links will be redirected to that page.

Using my own domain allows me to change it on the fly without the need to deploy a new version.

**Comment by ohadschn** [comment]
Hey,

Unfortunately if your domain is down for whatever reason, a redirect will also fail. In addition, you would have to keep updating those GitHub release builds when new ones come out, rather than let the package managers worry about it...

I realize this issue might be involved, but please see my related issue with a simple concrete suggestion that should cover what I believe is the vast majority of users (Pareto principle): https://github.com/tomaszzmuda/Xabe.FFmpeg/issues/298

**Comment by tomaszzmuda** [comment]
This package cannot be used in Xabe.FFmpeg.
1. It's nupkg so it will require code change - it's achievable so no problem
2. Size of the package - 139mb is a bit much
3. It contains only X builds and additional source will be required

I wish I could deploy it somewhere else but direct links can change sometimes (for example old GitHub pages when you got 404 after redirect from google) and this is the best source I can trust.

**Comment by ohadschn** [comment]
Hey,

1. Yeah `nupkg` is basically a zip file containing what I believe is the exact same artifact you're using in the full downloader (`ffmpeg-4.3.1-win32-static_x32.zip` / `ffmpeg-4.3.1-win64-static_x64.zip`), so like you said no problem.
1. In today's works an extra 70MB is almost always negligible but in principle I agree having different choco packages for x86/x64 would be nice, opened issue: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1551
1. By "X builds" you mean it contains only the static (full) builds? And when you say "additional source will be required", you mean some other link/package for the other build types (e.g. shared)? Again I agree in principle, this won't cover everything, but in reality the vast majority of people will be ok with the static build - I don't see an `ffmpeg-shared` choco package and I don't think anyone ever asked for one, so probably at least a 90/10 solution...

At the end of the day it is all about reliability, stability, and trust, like you said. I think the chocolatey API link is objectively the best option for Windows - certainly more than `ffbinaries.com` and respectfully more than `xabe.net`, redirection or not :) Simply too much depends on Chocolatey, its too mature and the community is too robust for it to change in a breaking way (I see 117 contributors and almost 10K commits).

So yeah, a perfect solution will be more involved, but fixing https://github.com/tomaszzmuda/Xabe.FFmpeg/issues/298 by changing the static download source to the chocolatey link along with a few lines of code to extract the zip from the nupkg would significantly increase reliability.
