### ISSUE TITLE
Upgrade Test & Sample projects to the latest .NET Core

### ISSUE THREAD

**Issue by ohadschn** [tomaszzmuda/Xabe.FFmpeg#299]
Any reason the following are .net core 2.x and not 3.1?

**_Xabe.FFmpeg.Test.csproj_**
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/d2487c793ef387a96da75da9f258cfdf3961c500/test/Xabe.FFmpeg.Test/Xabe.FFmpeg.Test.csproj#L4

**_SampleProject.csproj_**
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/d2487c793ef387a96da75da9f258cfdf3961c500/samples/SampleProject.csproj#L5

I actually had to upgrade the test project locally since the xUnit tests wouldn't run otherwise (complained about missing .NET Core SDK).

**Comment by tomaszzmuda** [comment]
It was the lowest possible version. Right now it should be probably set to use multiple target frameworks (if possible). I have to check that.
