### ISSUE TITLE
Trying to Render Frames to Video

### ISSUE THREAD

**Issue by forReason** [tomaszzmuda/Xabe.FFmpeg#300]
I am trying to use xabe.ffmpeg in one of my projects in order to render frames to video.

The documentation stated the following;
![image](https://user-images.githubusercontent.com/12736950/94275693-8eb1cf80-ff47-11ea-80b4-272572a2d9ba.png)

the first issue arises with `.SetPixleFormat`:
![image](https://user-images.githubusercontent.com/12736950/94275825-bdc84100-ff47-11ea-825d-7e20081d98a6.png)

so I tried to leave the Pixle format away which worked kind of. 
Current, "kind-of" working code:
```c#
List<string> files = Directory.EnumerateFiles(tempImageDirectory).ToList();
string outputName = "maprender.mp4";
if (File.Exists(outputName)) File.Delete(outputName);
Conversion.New()
    .SetInputFrameRate(1)
    .BuildVideoFromImages(files)
    .SetFrameRate(1)
    .SetOutput(outputName)
    .Start();
```

I tried to set `.SetFormat(format.mp4)` as well as `Format.h264` which both leave me with an mp4 video but the results are quite inconsistent:

```c#
Conversion.New()
    .SetInputFrameRate(1)
    .BuildVideoFromImages(files)
    .SetFrameRate(1)
    .SetOutputFormat(Format.h264)
    .SetOutput(outputName)
    .Start();
```

leaving .format away:
- Windows Media player can't play video
- VLC can play video
- Whats app computer can play video
- Whats app phone cant play video

with format.h264
- media player can play video
- vlc can play video
- whats app does not even recognize its a video
- phone media player cant play vieo

is there a way to get out an mp4 video which can be played on almost any device? (Such as all mp4 files I know of)

best regards,

Julian

**Comment by tomaszzmuda** [comment]
Hello,

As I see you have some problems with versions.
Do you installed both Xabe.FFmpeg.Downloader and Xabe.FFmpeg?
Please upgrade both version to latest one and try again with SetPixelFormat.
