### ISSUE TITLE
[Question] How to create video and append screenshots

### ISSUE THREAD

**Issue by LiorBanai** [tomaszzmuda/Xabe.FFmpeg#301]
Hi,
In my application I take 4 screenshots every second and at the end I create 1 video of those images. The problem is that for 30 minutes the creation of the video takes long time and the cpu usage is around 60% for the duration of the process..

Is there a way to create video during the screenshot creations? meaning start the video at the start and just append screenshots to the video as they are taken/created?

**Comment by tomaszzmuda** [comment]
Hello,
I'm not sure if it would be possible using FFmpeg. As I know the whole content of video has to be known before it could be converted. If you find how it can be done by FFmpeg I will help you use it in C#.

**Comment by veler** [comment]
Hi,
I think it's impossible using ffmpeg.exe in command line. Should either use a pipe or the avcodec library.
