### ISSUE TITLE
Add custom filters?

### ISSUE THREAD

**Issue by FrenziedIM** [tomaszzmuda/Xabe.FFmpeg#303]
Is it possible to add customer filters like colorbalance?

https://ffmpeg.org/ffmpeg-filters.html#colorbalance

**Comment by GramCreator** [comment]
Thank you :)

**Comment by GramCreator** [comment]
Hi @tomaszzmuda , I'm adding this as a string in the "parameter" part of the method:

I'm getting this issue:

colorbalance=rs=0.4:rm=0.4:rh=0.4:gs=0.08:gm=0.08:gh=0.08:bs=-0.06:bm=-0.06:bh=-0.06

[NULL @ 000001f42dffdc80] Unable to find a suitable output format for 'colorbalance=rs=0.27:rm=0.27:rh=0.27:gs=-0.04:gm=-0.04:gh=-0.04:bs=0.01:bm=0.01:bh=0.01'
colorbalance=rs=0.27:rm=0.27:rh=0.27:gs=-0.04:gm=-0.04:gh=-0.04:bs=0.01:bm=0.01:bh=0.01: Invalid argument

**Comment by tomaszzmuda** [comment]
ConversionResult or exception has property with all parameters. Can you paste content of it here?
![image](https://user-images.githubusercontent.com/13612984/96085543-42600c80-0ec1-11eb-82a7-f16468e232c1.png)

**Comment by GramCreator** [comment]
The only way to do that was to remove any parameters in the method.

Here is the Arguments return string: 

`-i "C:\Users\TT\source\repos\Test\Test\bin\Debug\Videos\StokeCompressed.mp4" -y -threads 16 -preset ultrafast -s 434x734 -map 0:0 -map 0:1 "NewVideos\StokeCompressed.mp4"`

**Comment by GramCreator** [comment]
Edit: Fixed it by adding -vf before the colorbalance command.

Now my new issue is that it doesn't apply the color balance. However, if we remove resizing from the ffmpeg code, and leave color balance only it works perfectly. Like this:

bin/bin/ffmpeg.exe -i descarga.mp4 -vf "colorbalance=rs=-0.07:rm=-0.07:rh=-0.07:gs=0.34:gm=0.34:gh=0.34:bs=0.07:bm=0.07:bh=0.07" output.mp4

Is it not possible to have colorbalance + resize, and if so, is there a way around this? @tomaszzmuda 

Sorry to bother you, and thanks for all the help thus far.

**Comment by tomaszzmuda** [comment]
Hey,

I found this: https://video.stackexchange.com/questions/23866/how-to-combine-ffmpeg-vf-commands-for-resizing-and-color-correction
Have you seen that?
