### ISSUE TITLE
Duration of audio/video stream have the millisecond component removed, why?

### ISSUE THREAD

**Issue by micdah** [tomaszzmuda/Xabe.FFmpeg#304]
Looking in the code, I can see that the millisecond component of the audio/video duration is removed, why is this?

See here: https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/d2487c793ef387a96da75da9f258cfdf3961c500/src/Xabe.FFmpeg/Probe/FFprobeWrapper.cs#L68

We are experiencing issues where the reported duration of an audio file is incorrect, becuase the millisecond component has been removed - which has led to issues as we always check if the parts we are about to extract are contained within the file - but when we want to extract right up to the end, we hit this issue as the true end contains milliseconds.

Also, only removing the millisecond component, still leaves anything less than a millisecond! So even if this is what is wanted, it is incorrect. For example one of our failed files is reported as being `148.0009999` seconds long, the actual length is `148.896`

**Comment by tomaszzmuda** [comment]
I think it was removed due to test instability. 
I'm going to check that. Probably this line (and line with videoDuration) can be removed but there are plenty tests to change.

**Comment by tomaszzmuda** [comment]
Hey,
Look at this Pull Request please: #311

**Comment by michaelnimbs** [comment]
Hey @tomaszzmuda,
when is the next release planned? Really need this fix, thanks!

**Comment by tomaszzmuda** [comment]
I've planned to release it with one more feature to current release but it's not ready. 
I'm going to release new version today or tomorrow.
