### ISSUE TITLE
Possible NullReferenceException

### ISSUE THREAD

**Issue by Vodolazz** [tomaszzmuda/Xabe.FFmpeg#31]
Hi!

https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/a2c43938746a0439c5fddba16b7bc7ec48a837a7/Xabe.FFmpeg/FFprobe.cs#L22

if JsonConvert.DeserializeObject<ProbeModel> returns null, this line would cause null reference exception.
such thing may happen if, for example, provided file mime type will not be recognized by ffprobe.
In that case it would be great to initialize Properties with null reference so it should be possible to check if file was recognized or not without wrapping first call to properties into try catch block.

**Comment by tomaszzmuda** [comment]
Hello, I'll make change it soon.
Probably Properties won't be nullable but if file is not recognized by ffprobe all values in Properties will be null. I have to consider all options.

**Comment by Vodolazz** [comment]
yeah, that's definitely a reasonable option too.

**Comment by tomaszzmuda** [comment]
I have just release new version with null Properties when file format is incorrect.
This will be changed in 3.0 version but at this time is the best option without changing api so far.
