### ISSUE TITLE
Is it possible to specify a output directory for ExtractEveryNthFrame?

### ISSUE THREAD

**Issue by Drunkar** [tomaszzmuda/Xabe.FFmpeg#310]
When I add path info to the outputFileNameBuilder, it fails in FFmpegNoSuitableOutputFormatFoundException: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers.
Are there any ways to set output folder for ExtractEveryNthFrame?

Failed:
```
string outputPath = "c:/Temp/";
IMediaInfo mediaInfo = await Xabe.FFmpeg.FFmpeg.GetMediaInfo("video.mp4");
IStream videoStream = mediaInfo.VideoStreams.First();
System.Func<string, string> outputFileNameBuilder = (number) => { return outputPath + number + ".png"; };
Xabe.FFmpeg.IConversionResult conversionResult = await Xabe.FFmpeg.FFmpeg.Conversions.New()
    .AddStream(videoStream)
    .ExtractEveryNthFrame(10, outputFileNameBuilder)
    .Start();
```

Successed:
```
IMediaInfo mediaInfo = await Xabe.FFmpeg.FFmpeg.GetMediaInfo("video.mp4");
IStream videoStream = mediaInfo.VideoStreams.First();
System.Func<string, string> outputFileNameBuilder = (number) => { return number + ".png"; };
Xabe.FFmpeg.IConversionResult conversionResult = await Xabe.FFmpeg.FFmpeg.Conversions.New()
    .AddStream(videoStream)
    .ExtractEveryNthFrame(10, outputFileNameBuilder)
    .Start();
```

**Comment by tomaszzmuda** [comment]
Hello,
I made a test ant it's work correctly.
![image](https://user-images.githubusercontent.com/13612984/96746158-2e3b7400-13c7-11eb-91ee-7871d5f78be7.png)
This is code I used.

--------------
Even your code works properly:
![Uploading image.png…]()

**Comment by Drunkar** [comment]
Thank you for checking. 
Ah I found why it failed...
my temp file name was lower case. Sorry for the rudimentary mistake.
