### ISSUE TITLE
Understanding Inputs

### ISSUE THREAD

**Issue by ghendo** [tomaszzmuda/Xabe.FFmpeg#314]
I have all my input files in aws S3 which means the input is a stream. It seems that the input to xabe.ffmpeg is always a file?
Does this mean I need to save the S3 object as a file on the local disk to use it?

**Comment by tomaszzmuda** [comment]
Hello @ghendo 

Look at this example:
![image](https://user-images.githubusercontent.com/13612984/98849955-5103fa00-2454-11eb-91a0-8bb3245b4b41.png)

Just user URL of that file as input file (as I know FFmpeg has some problems with HTTPS so use HTTP instead)
