### ISSUE TITLE
Conversion Prefix Params

### ISSUE THREAD

**Issue by shravan2x** [tomaszzmuda/Xabe.FFmpeg#315]
This library currently supports passing in parameters in `conversion.Start()` which are postfixed to the conversion command. I would like pin the conversion to a specific core using taskset. To do this I could prefix the command with `taskset 1 `. Can a separate method be added to _prefix_ text like this?

**Comment by tomaszzmuda** [comment]
You cannot do that using the library.
![image](https://user-images.githubusercontent.com/13612984/99911393-57b42c00-2cf4-11eb-8b90-6cee89971f8c.png)
Is not sufficient?
