### ISSUE TITLE
Enhancement: Support Chapters

### ISSUE THREAD

**Issue by PhotoKevin** [tomaszzmuda/Xabe.FFmpeg#317]
Would it be possible to add support for reading/setting chapter marks?

I grepped the source code and couldn't find anything existent.

**Comment by tomaszzmuda** [comment]
Hey,

Right now you can add that manually using AddParameter method.
If you want something more sophisticated, write here how it should looks like (We don't have any experience with chapters).
We will try to implement this or wait for Pull Request :)
