### ISSUE TITLE
FFmpegDownloader.GetLatestVersion not working

### ISSUE THREAD

**Issue by nmaroine** [tomaszzmuda/Xabe.FFmpeg#318]
Hi,
I'm trying to make a simple concatenation of two videos, but I have the error 

Cannot find FFmpeg in [Folder]

My code is simple

```
        static void Main(string[] args)
        {
            FFmpeg.SetExecutablesPath(".");
            FFmpegDownloader.GetLatestVersion(FFmpegVersion.Official,".");
            FFmpeg.SetExecutablesPath(".");
            string firstFile = @"ressources\1.mp4";
            string secondFile = @"ressources\2.mp4";
            string output = @"ressources\3.mp4";
            var result = Conversion.Concatenate(output, firstFile, secondFile).Result;
        }
```

I dont know what I did miss here, any idea plz ?

I'm Using .net core 3.1
on windows 10

![image](https://user-images.githubusercontent.com/17453646/102692163-ddeb6180-4211-11eb-9ab9-94ceae969f38.png)
![image](https://user-images.githubusercontent.com/17453646/102692166-e6dc3300-4211-11eb-9f39-a94e32427ab9.png)

**Comment by tomaszzmuda** [comment]
Hey,
FFmpegDownloader.GetLatestVersion(FFmpegVersion.Official,".") - this method should be awaited.

Use:
await FFmpegDownloader.GetLatestVersion(FFmpegVersion.Official,".");
or if you can't await that
FFmpegDownloader.GetLatestVersion(FFmpegVersion.Official,".").GetAwaiter().GetResult();

**Comment by nmaroine** [comment]
Working 100% ty for the fast answer!
