### ISSUE TITLE
Get video from IP camera (rtsp)

### ISSUE THREAD

**Issue by NapalmRain** [tomaszzmuda/Xabe.FFmpeg#320]
Hi!
Help me please, how i can get video from IP camera and save it into file?
In your FAQ i found answer: `You can listen on online streams using **WebStream**. Just add it to your conversion object.`
But i don't understand it.. What is WebStream?

Can you please give me some example of code? I have only URL of camera stream.

Thank you!

**Comment by tomaszzmuda** [comment]
Hello,

Sorry, that one section in FAQ is outdated (I'm going to update it ASAP).
Please use "normal" flow of conversion. Instead of passing file name to MediaInfo - paste URL to stream.
IMediaInfo mediaInfo = await FFmpeg.GetMediaInfo("rtsp://127.0.0.1");

**Comment by NapalmRain** [comment]
Thank you!
