### ISSUE TITLE
use stdin / stdout?

### ISSUE THREAD

**Issue by mgamache** [tomaszzmuda/Xabe.FFmpeg#322]
Is there a way to use Xable with stdin / stdout to provide media for processing and/or receive processed media? Thanks for your help.

**Comment by tomaszzmuda** [comment]
Hey,

In **OnDataReceived** event you have stdout. I discourage sending anything by your own to FFmpeg but you can have processId assigned to conversion so you can attach to process (you will get process id with event) and send what do you want to it.

**Comment by tomaszzmuda** [comment]
Yeah, during implementation we got so many problems with process managing so right now I make changes in that part only when I have to. If you need something special that can be used be other people too you can create Pull Request with that and I will help.

**Comment by mgamache** [comment]
thanks.
