### ISSUE TITLE
[Survey] What do you need

### ISSUE THREAD

**Issue by tomaszzmuda** [tomaszzmuda/Xabe.FFmpeg#323]
We would be very glad if you can spend 3 minutes of your time to fulfill a short form about your experience with Xabe.FFmpeg. It will help us develop product that is needed on market with the functionalities you want!

https://docs.google.com/forms/d/1_3BvdpEkywhjWcDpLlve213mRL-eo-p7sGxaf5YJTSU/viewform?gxids=7628&edit_requested=true

**Comment by 06needhamt** [comment]
I've just filled it in. I hope the responses will be useful.
