### ISSUE TITLE
Nuget Error when installing package

### ISSUE THREAD

**Issue by aykuter** [tomaszzmuda/Xabe.FFmpeg#33]
Hey. I hope this is the right place for this kind problem if it's not i'm sorry. I'm new to github community. I want to use ffmpeg wrapper but i couldn't manage to install nuget package. 

```
PM> Install-Package Xabe.FFMpeg -Version 2.2.7
Installing 'Xabe.FFmpeg 2.2.7'.
Successfully installed 'Xabe.FFmpeg 2.2.7'.
Adding 'Xabe.FFmpeg 2.2.7' to WindowsFormsApplication1.
Uninstalling 'Xabe.FFmpeg 2.2.7'.
Successfully uninstalled 'Xabe.FFmpeg 2.2.7'.
Install failed. Rolling back...
Install-Package : Could not install package 'Xabe.FFmpeg 2.2.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not conta
in any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Xabe.FFMpeg -Version 2.2.7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

I hope you can help me i'm totally lost right now. Thank you!

**Comment by tomaszzmuda** [comment]
Hello. This package is using .NET Standard 2.0.
You have to change target project to .NET Framework 4.6.1 or higher. I think this is the problem.
What version of .NET Framework your project is targeting?
If changing target version won't help you can install .NET Core SDK 2.0 od higher.

**Comment by aykuter** [comment]
I have .NET Core SDK 2.0.3 and changing my project to .NET Framework 4.6.1 didn't help either. Here is a screenshot : 

https://imgur.com/a/q6DPj

I hope you have more answers for me :) Thanks!

**Comment by tomaszzmuda** [comment]
Could you tell me what version of .NET Framework is installed on your PC?

**Comment by aykuter** [comment]
I just installed 4.7.1 but nothing changed. I have VS 2013 it's not a problem right ? Do i need newer VS version like 2015 or 2017 ?

**Comment by tomaszzmuda** [comment]
According to [this](https://github.com/dotnet/announcements/issues/24) the minimum version of VisualStudio if you want to contribute is 2017 15.3. 
If you want to use package you have to get NuGet version 3.6 or higher. I don't know if it will work on VS2013 but you could try.
Please let me know if it works.

**Comment by lkischler** [comment]
Hello,
I tried reproduce your issue. First I use VS 2013 with some old nuget version. FFmpeg library was not found so i update nuget to the newst version. I found library but installation failed so I open the same solution in VS 2017 and try install by nuget and it is end with success. 

Probalby it is a problem with nuget for VS 2013 so I agree with @tomaszzmuda to use VS 2017 15.3 and .NET 4.6.1

**Comment by aykuter** [comment]
Ahh how i couldn't see that requirement. Thank you so much for your help. I manage to install Xabe.FFmpeg but now i have compile errors even with empty project. 

https://imgur.com/a/qmefI

Do you have any suggestion ?

**Comment by aykuter** [comment]
@lkischler Hey. Thank you so much for your effort. I update my NuGet version for VS 2015 then i try to install Xabe.FFmpeg it's installed successfully. But i have weird compile problems. I  think i should go with VS 2017 ?

**Comment by tomaszzmuda** [comment]
This is the best option.
I'll manage how is minimum requirements to get this works.

**Comment by aykuter** [comment]
Yep it's working with VS 2017. Thank you guys!
