### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by mcopur** [tomaszzmuda/Xabe.FFmpeg#333]
Hi,

I am trying to extract audio from a video from ".m3u8" URL. It works with this command which is stated below but I could not find how can I do that with your library. Is that possible? If so, could you please help me with that?

`ffmpeg -i "https://blablabla/playlist.m3u8" -acodec mp3 -ab 128k test.mp3`

**Comment by tomaszzmuda** [comment]
Hey,
There is a SaveM3U8Stream method.
![image](https://user-images.githubusercontent.com/13612984/107765740-a5a86100-6d32-11eb-801e-df44d7e51e17.png)

**Comment by mcopur** [comment]
@tomaszzmuda  thanks, I tried SaveM3U8Stream method first, it worked only "mp4". When I used "mp3" as an output format id did not work and I got a conversion error. I asked also on [StackOverflow](https://stackoverflow.com/questions/66170117/extracting-audio-from-a-video-from-m3u8-url) and I found the answer myself. I hope that approach is the correct one. If there is a better way, please let me know.

```
internal class Program
    {
        private static string link = "yourlink/playlist.m3u8";

        private static async Task Main(string[] args)
        {
            var mediaInfo = await FFmpeg.GetMediaInfo(link);
            var conversion = await FFmpeg.Conversions.FromSnippet.ExtractAudio(mediaInfo.Path, "test.mp3");
            conversion.OnProgress += async (sender, args) =>
            {
                await Console.Out.WriteLineAsync($"[{args.Duration}/{args.TotalLength}][{args.Percent}%]");
            };

            await conversion.SetAudioBitrate(128000).SetOutputFormat(Format.mp3).Start();

            Console.ReadKey();
        }
    }
```
