### ISSUE TITLE
Create video from images

### ISSUE THREAD

**Issue by md84419** [tomaszzmuda/Xabe.FFmpeg#338]
I have a bunch of raw framebuffer images in a Queue<byte[]> called frameQueue.

I want to create a new video directly from this queue, without first writing out each frame to disk as a bitmap.

How can I do that, please?

I guess I want something like:

string videoPath = persistentDataPath + "/video" + ".mp4";

IConversion ic = FFmpeg.Conversions.New();

while(frameQueue.Count > 0) {
    // raw uncompressed 32-bit framebuffer image data without headers
    ic.BuildVideoFromFramebuffer(screenWidth, screenHeight, frameQueue.Dequeue());
}

ic.SetOutput(videoPath);
ic.Start();

?

**Comment by tomaszzmuda** [comment]
Hi,

Right now it's not possible to do it with Xabe.FFmpeg. It doesn't support in-memory processing.
I'm not even sure if it's possible on Windows using only FFmpeg.

**Comment by md84419** [comment]
I think it is possible through the FFMPEG API.  See ffmpeg/doc/examples/muxing.c

Accord used to provide a VideoFileReader and Writer low-level: http://accord-framework.net/docs/html/N_Accord_Video_FFMPEG.htm

**Comment by tomaszzmuda** [comment]
As I see VideoFileReader works only on saved files.
I know that FFmpeg API allows that by for e.g. named pipes. I haven't tried it on Windows yet.
