### ISSUE TITLE
Timespan does handle millisecond

### ISSUE THREAD

**Issue by lreben** [tomaszzmuda/Xabe.FFmpeg#344]
When using a TimeSpan with millisecond the library freezes. I can still add it with add parameter though,

**Comment by tomaszzmuda** [comment]
Hey,
I've created PR with some tests.
#349 Everything looks fine

**Comment by lreben** [comment]
Hmm, it only caused a problem with a millisecond other than 0 on my side. Odd!

**Comment by tomaszzmuda** [comment]
Can you share exact TimeSpan that cause the issue? I'm going to write test for that.

**Comment by lreben** [comment]
Oof, this may be best if I simply send the entire project. I'm doing a rotoscoping project so the time stamp changes over time. Since we are talking standard video, it should be 966 or 2 the first time I call it depending on how. I has been over a month since I hit this problem and switched to adding a text parameter,.
