### ISSUE TITLE
FFmpegDownloader.GetLatestVersion(FFmpegVersion.Official) does not download to FFmpeg.ExecutablePath

### ISSUE THREAD

**Issue by broderickhyman** [tomaszzmuda/Xabe.FFmpeg#347]
The comment on the static method `FFmpegDownloader.GetLatestVersion(FFmpegVersion version, IProgress<ProgressInfo> progress = null);` says that it will download to the executable path when set. It instead just downloads to "." in all cases.

**Comment by tomaszzmuda** [comment]
Thanks @broderickhyman 
I've changed the xml docs.
#348 there is a pull request for that. If you have more suggestions just tell.
That would be changed in 5.0 version to download it to FFmpeg.ExecutablesPath (cannot do that right now due to compatibility issues)
