### ISSUE TITLE
Conversion.AddParameter add "-ss"(or "-t") only once.

### ISSUE THREAD

**Issue by aleadpay** [tomaszzmuda/Xabe.FFmpeg#360]
I have several inputs but I need only a slice of each one, for example:

    ffmpeg -ss 00:03:30 -t 00:00:05 -i a.mp4 -ss 00:10:00 -t 00:00:05 -i b.mp4 -ss 00:15:00 -t 00:00:05 -i c.mp4 -filter_complex ........ output.mp4

but when I call Conversion.AddParameter("-ss xx:xx:xx -t xx:xx:xx -i x.mp4") several times, only one parameter is added.

**Comment by tomaszzmuda** [comment]
I have made change in #363 it should be pushed to NuGet in next 2 days
