### ISSUE TITLE
Exec format Error on Ubuntu

### ISSUE THREAD

**Issue by kafeinarge** [tomaszzmuda/Xabe.FFmpeg#364]
Hi,

I've seen an issue opened before on this topic but i keep getting error.  When I want to use it on Ubuntu server, I get a warning as follows. 

![image](https://user-images.githubusercontent.com/23554188/119997843-d27a3e80-bfd8-11eb-9bf9-32de4ef66933.png)

I think there are missing files I need to download for ubuntu. I used to following method and downloaed files.

![image](https://user-images.githubusercontent.com/23554188/119999265-37826400-bfda-11eb-91eb-899de73ab46f.png)
![image](https://user-images.githubusercontent.com/23554188/119999337-4f59e800-bfda-11eb-951d-a1000873a551.png)

How can I download files that can run on Ubuntu? 

Thank you very much in advance

**Comment by tomaszzmuda** [comment]
Hello,
Have you downloaded it on ubuntu? FFmpegDownloader gets the correct version for your OS.

**Comment by kafeinarge** [comment]
Sorry for my late reply. I did the download on Ubuntu. It's worked. Thanks a lot.
