### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by Junaid-Amjad** [tomaszzmuda/Xabe.FFmpeg#368]
Hi, 
I am using the library to fetch http/rtsp stream as indicated in the document [here](https://ffmpeg.xabe.net/docs.html)

```
string output = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + FileExtensions.Mp4);
var mediaInfo = await FFmpeg.GetMediaInfo("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov");

var conversionResult = await FFmpeg.Conversions.New()
    .AddStream(mediaInfo.Streams)
    .SetOutput(output)
    .Start();
```
I am using droidcam to view the result but after some period. This exception is thrown 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xabe.FFmpeg.FFprobeWrapper.SetProperties(MediaInfo mediaInfo, CancellationToken cancellationToken)
   at Xabe.FFmpeg.MediaInfo.Get(String filePath, CancellationToken cancellationToken)
   at Xabe.FFmpeg.MediaInfo.Get(String filePath)
   at Xabe.FFmpeg.FFmpeg.GetMediaInfo(String fileName)
```
It was odd to me as i checked everything but still this issue arises. It occurs at
            `var mediaInfo = await FFmpeg.GetMediaInfo(url);`
URL is active and i test it on FFMPEG but when i run it through Xabe.FFMPEG exception is thrown. Can you point out the problem or do you have any document related to the exceptions. Thanks in advance

**Comment by tomaszzmuda** [comment]
Hello @Junaid-Amjad 
Have you figured out how to resolve that issue? I've tried to reproduce it but it's not easy.
Can you tell me if you get that exception during conversion or before? MediaInfo is used at the beginning of conversion to get all required information about video and it shouldn't be used after that but if I get it right it's different in your case.

To reproduce that I installed droidcam and tried to save it and get media info of that and everything worked.

**Comment by HamsterExAstris** [comment]
I'm running into the same issue with some MP3 files on my NAS (so no HTTP/RTSP needed). I'm calling GetMediaInfo directly on them to get the media length when it throws, without doing any conversion at all.

Not all files are impacted. I'm working on determining if it's the same problem files on every run.

This behavior is new when upgrading from 4.3.0 to 5.0.2. ffmpeg executables appear to be the same (I use FFmpegDownloader to get the newest version on startup but the files are from 2019).

**Comment by Junaid-Amjad** [comment]
Hi @tomaszzmuda 
Unfortunately, i divert it into another task and did not follow up with the issue. To answer your question yes I get the exception before conversion. It occurs on `FFMPEG.GetMediaInfo`  and odd thing is that it occurs sometimes and sometimes it get the result as indicated by @HamsterExAstris . That's why i was curious about the exception NullReference, which value/field/property is null when we use droid or anyother URL.

**Comment by tomaszzmuda** [comment]
It would be awesome if you can provide one of these files. I'll try to debug it and check what's going on
