### ISSUE TITLE
Downloading M3U8 Streams

### ISSUE THREAD

**Issue by InteXX** [tomaszzmuda/Xabe.FFmpeg#371]
Can this tool be used to download an M3U8 stream?

For example, here's the command line I've been using:

```
ffmpeg -i https://domain.com/directory/playlist.m3u8 -c copy "D:\TargetFolder\TargetVideo.mp4"
```

But I'd like to move the task into managed code, hopefully with progress reporting.

What would be the `Xabe.FFmpeg` equivalent for this?

**Comment by tomaszzmuda** [comment]
Hello @InteXX 
Look at M3U8 section at [documentation](https://ffmpeg.xabe.net/docs.html).

**Comment by InteXX** [comment]
Very good, thank you. This is exactly what I need.
