### ISSUE TITLE
Can’t find Ffmpeg.GetLatestVersion()

### ISSUE THREAD

**Issue by zydjohnHotmail** [tomaszzmuda/Xabe.FFmpeg#374]
Hello:
I found this package, it is a good one, but I need some help on how to use it.
My OS is: Windows 10 with latest updates, I am using C# with Visual Studio 2019 version 16.10.3; I have downloaded latest version of FFMPEG, and install its binary in 
C:\Program Files\ffmpeg-n4.4-78-g031c0cb0b4-win64-gpl-4.4\bin\ffmpeg.exe
I installed nuget package of version 5.0.2:
PM> Install-Package Xabe.FFmpeg -Version 5.0.2
The following is my code: (C# console app targeting .net 5.0 for x64 CPU)

using System.Threading.Tasks;
using Xabe.FFmpeg;

namespace XabeDownloadBinary
{
    class Program
    {
        static async Task Main()
        {
            FFmpeg.ExecutablesPath = _ffmpegDir;
            await FFmpeg.GetLatestVersion();
        }
    }
}

However, I got the following compile errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'FFmpeg' does not contain a definition for 'GetLatestVersion'XabeDownloadBinary	C:\XabeDownloadBinary\XabeDownloadBinary\Program.cs	11	Active
Error	CS0200	Property or indexer 'FFmpeg.ExecutablesPath' cannot be assigned to -- it is read only	XabeDownloadBinary	C:\XabeDownloadBinary\XabeDownloadBinary\Program.cs	10	Active
Error	CS0103	The name '_ffmpegDir' does not exist in the current contextXabeDownloadBinary	C:\SportsVideos\XabeFFMpeg\XabeDownloadBinary\XabeDownloadBinary\Program.cs	10	Active

From my understanding, the package didn’t have GetLatestVersion() method.
Please advise on how to fix this issue.
Thanks,

**Comment by giangcoi48k** [comment]
install package Xabe.FFmpeg.Downloader and use FFmpegDownloader.GetLatestVersion(FFmpegVersion.Official)

**Comment by javierpaz2000** [comment]
Hi
and about the other error
Error CS0200 Property or indexer 'FFmpeg.ExecutablesPath' cannot be assigned to -- it is read only XabeDownloadBinary

you need to use FFmpeg.SetExecutablesPath("  ... the path to your ffmpeg ...");
