### ISSUE TITLE
How I can use ffmpeg parameter vstack?

### ISSUE THREAD

**Issue by zydjohnHotmail** [tomaszzmuda/Xabe.FFmpeg#379]
Hello:
I found I can use the following ffmpeg to merge/overly 2 vidoes, so that the first video is on top of the second video.  The condition is that the both videos have almost the same duration and the same screen width.

C:\Videos>ffmpeg -i 1.mp4 -i 2.mp4 -filter_complex vstack -vsync 2 output.mp4

I want to know if I can use this repo to do the same as the ffmpeg command?
Thanks,

**Comment by tomaszzmuda** [comment]
It can be done using AddParameter
