### ISSUE TITLE
Using a network location as output doesn't work in version 4.x or above

### ISSUE THREAD

**Issue by Gamingdevil** [tomaszzmuda/Xabe.FFmpeg#381]
I'm trying to do rtp streaming with the latest version of Xabe.FFmpeg. I've been able to do this successfully in the past, with version 3.6.2.

                   audioStream.UseNativeInputRead(true);

                    if (!string.IsNullOrEmpty(parameters.Codec)) audioStream.SetCodec(parameters.Codec);
                    if (parameters.Channels > 0) audioStream.SetChannels(parameters.Channels);
                    if (parameters.Bitrate > 0) audioStream.SetBitrate(parameters.Bitrate);
                    if (parameters.SampleRate > 0) audioStream.SetSampleRate(parameters.SampleRate);
                    if (!string.IsNullOrEmpty(parameters.Compander)) audioStream.SetInputFormat(parameters.Compander);

                    var conversion = FFmpeg.Conversions.New().AddStream(audioStream);

                    conversion.AddParameter("-f rtp").SetOutput(target);

                    var output = conversion.Build();
                    await conversion.Start();
The target variable is something like "localhost:8080". I'm getting an error when calling `Start`: 
"System.ArgumentException: Path cannot be the empty string or all whitespace. Parameter name: path".

Stacktrace
`   at System.IO.Directory.CreateDirectory(String path)
   at Xabe.FFmpeg.Conversion.CreateOutputDirectoryIfNotExists()
   at Xabe.FFmpeg.Conversion.<Start>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter```1.GetResult()`

When looking through the source code of `CreateOutputDirectoryIfNotExists` the problem appears to be that the output directory is always created, even when the target is not a file location and then System.IO throws the above error, which isn't caught by the code.

I suggest either checking if the target is actually a file location, or simply catching the ArgumentException, to resolve this.

**Comment by tomaszzmuda** [comment]
Hello,
If you add "rtsp://" before localhost it will work. 
I'm going to make it more user friendly.

**Comment by Gamingdevil** [comment]
> If you add "rtsp://" before localhost it will work.

That does seem to work, thank you.
