### ISSUE TITLE
"Acces Denied" on Android (xamarin)

### ISSUE THREAD

**Issue by IcySnex** [tomaszzmuda/Xabe.FFmpeg#382]
My issue is that my app always crashes (throws an exception) whenever I try to convert a webm file to mp3.
Im using this code:
```
string ffmpeg = @"/storage/emulated/0/ffmpeg";
FFmpeg.SetExecutablesPath(ffmpeg);
await FFmpegDownloader.GetLatestVersion(FFmpegVersion.Android, ffmpeg);

await FFmpeg.Conversions.New().Start($"-i \"{temppath}\" -vn \"{fullpath}\"");
```
And Im getting this exception:
```
System.ComponentModel.Win32Exception: 'ApplicationName='/storage/emulated/0/ffmpeg/ffmpeg', CommandLine='-i "/storage/emulated/0/myfolder/song.webm" -vn "/storage/emulated/0/myfolder/song.mp3"', CurrentDirectory='', Native error= Access denied'
```

Yes, I downloaded the android ffmpeg binarys and they exist in the path. I also set the executablesp path with FFmpeg.SetExecutablesPath();. I also have acces to the storage.
I tried this libary on windows and everything just worked fine, I really dont know why Im getting this error on the android plattform. Any help is really appreciated, thanks!

**Comment by techmaticsnz** [comment]
Im also getting this error, so would appreciate if you had any information how to fix it. thanks!

**Comment by kaszasat** [comment]
@IcySnex @techmaticsnz 
Any solution that doesn't involve ADB?

**Comment by IcySnex** [comment]
@kaszasat @techmaticsnz
I have ditched this library and wrote my own FFMPEG code for downloading the binaries and processing the FFMPEG command.

You can use the ```Java.Lang.Runtime.GetRuntime().Exec(..);``` function to execute custom linux commands on android with xamarin. Be sure to execute ```chmod 777 {file}``` on the file before youre trying to process.

I have used this an an example project (its really outdated and ugly code but the base is working): https://github.com/IcySnex/SpotiDown/blob/main/Android/SpotiDown/SpotiDown.Android/HelperService.cs#L61
