### ISSUE TITLE
[Question]From which version onward changed the licencing for Xabe.FFmpeg

### ISSUE THREAD

**Issue by sikri-eic** [tomaszzmuda/Xabe.FFmpeg#390]
Hi,

I see that your project is no longer free for commercial use. I have no problems with that. If I remember correctly, it was free of charge in some of the earlier versions. If so, when did the license change (at which version of the NuGet package)?

Or maybe I'm misremembering and it was never free for commercial use?

(I don't plan using an older version of the package just to get something free of charge, but if there was a change in the license I want to learn about that.)

**Comment by tomaszzmuda** [comment]
Hey,

The last version deployed before the license change was 2.2.5 at end of 2017. I think it's a bit outdated, but probably it's still functional.

**Comment by sikri-eic** [comment]
Thank you for the quick response.
