### ISSUE TITLE
Xamarin Support

### ISSUE THREAD

**Issue by claudiocleberson** [tomaszzmuda/Xabe.FFmpeg#40]
Hi @tomaszzmuda ,

Do you have any plan to turn that library compatible with Xamarin apps?

regards,
Claudio.

**Comment by tomaszzmuda** [comment]
Hello.
I haven't planed it at all. I haven't done anything in Xamarin so I don't know what to do.
According to .NET Standard documentation this should works on Xamarin but I don't know how to get ffmpeg executables on mobile devices. I realy want to make it portable but this will take long time. 
If you need this and know the solution talk to me at glitter, I'll try do something with it.

**Comment by claudiocleberson** [comment]
Thanks Man, I Like a lot that you created something with an awesome doc section, a Lot of library out there miss that point. I'm searching for something that can run with Xamarin app, so that would be necessary to have the binary inside. I am not a expert enough to create that, otherwise I would contribute with your project.

**Comment by tomaszzmuda** [comment]
I have made some research and implementing it on Xamarin wouldn't be easy.
I read some articled and they say FFmpeg isn't the best option to convert media in mobile devies (you still could install .NET Standard 2.0 package on mac xamarin project).
I don't have time to develop project in this direction so probably it wouldn't ever works on mobile devices.
