### ISSUE TITLE
Documentation examples not working in .NET 6

### ISSUE THREAD

**Issue by AlessandroMartinelli** [tomaszzmuda/Xabe.FFmpeg#408]
Hi,
I've downloaded Xabe.FFmpeg 5.1 from NuGet in a .NET 6 application.

However even the first example of the documentation (https://ffmpeg.xabe.net/docs.html) does not work
```
string output = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".mp4");
var snippet = FFmpeg.Conversions.FromSnippet.Convert(Resources.MkvWithAudio, output);
IConversionResult result = await snippet.Start();
```
The compiler finds an error in `FFmpeg.Conversions.FromSnippet`; _An Object reference is required for the non-static field, method or property 'Conversions.FromSnipper'_. It make sense because
 `Xabe.FFmpeg.Conversions` is not a static class and therefore it cannot be used like above (see class code below). Furthermore, since it its constructor is not public, it cannot be instantiated either, so I really have no idea about how to use it.
```
namespace Xabe.FFmpeg
{
    public class Conversions
    {
        //
        // Summary:
        //     Get new instance of Conversion
        //
        // Returns:
        //     IConversion object
        public Snippets FromSnippet = new Snippets();

        //
        // Summary:
        //     Get new instance of Conversion
        //
        // Returns:
        //     IConversion object
        public IConversion New() {
            return Conversion.New();
        }

        internal Conversions() {
        }
    }
}
#if false // Decompilation log
```
Furthermore, `Resources` is not recognized, and it is not clear to which class it belongs to.

Could you please tell me what am I missing?

Thank you

**Comment by tomaszzmuda** [comment]
Hello,

It looks like a problem with namespaces and naming. 
Try to use this:
Xabe.FFmpeg.FFmpeg.Conversions.FromSnippet.Convert(Resources.MkvWithAudio, output);
