### ISSUE TITLE
SetInput method not found

### ISSUE THREAD

**Issue by CodingOctocat** [tomaszzmuda/Xabe.FFmpeg#412]
My code:
![微信截图_20220404163135](https://user-images.githubusercontent.com/7220248/161505331-db62b98a-8387-4ee5-af20-0bfb8325e1f4.png)

Official docs:
![微信截图_20220404163236](https://user-images.githubusercontent.com/7220248/161505592-c9bad85c-402d-4527-910e-e4289bf8ffbc.png)

**Comment by exopole** [comment]
Did you find an answer ? I got the same issue...

**Comment by tomaszzmuda** [comment]
Hello,
It changed some time ago.
Try using AddStream instead of SetInput:
```csharp
            var outputPath = "test.mp4";
            var mediaInfo = await MediaInfo.Get(Resources.MkvWithAudio);
            IConversionResult conversionResult = await FFmpeg.Conversions.New()
                .AddStream(mediaInfo.Streams)
                .AddParameter($"-ss {TimeSpan.FromSeconds(1)} -t {TimeSpan.FromSeconds(1)}")
                .AddParameter("-s 1920x1080")
                .SetOutput(outputPath)
                .Start();
```
                
I'm going to update documentation.

**Comment by exopole** [comment]
Hello,

Thank you. It works now.
