### ISSUE TITLE
Is there way to add transition between images when generating mp4 

### ISSUE THREAD

**Issue by vanaja9966** [tomaszzmuda/Xabe.FFmpeg#414]
var tr = $"-filter_complex 'xfade=transition =fadeblack:duration = 1:offset = 4.5'";
            IConversionResult conversionResult = await FFmpeg.Conversions.New()
            .SetOverwriteOutput(true)
            .SetInputFrameRate(0.3)
            .BuildVideoFromImages(imageFiles)
            .SetFrameRate(20)
            .AddParameter($"{tr}\"", ParameterPosition.PostInput)
            .SetPixelFormat(PixelFormat.yuv420p)
            .SetOutput(output.mp4)
            .Start()
Unable to get video while adding filter_complex. Is there method we can add Transition between images.

**Comment by tomaszzmuda** [comment]
Hello,

It's a quite complicated query. In that case, I would suggest using direct arguments to pass it to ffmpeg.
