### ISSUE TITLE
When using single file deployment, failed to find ffmpeg executables in the path where the application is in

### ISSUE THREAD

**Issue by deadcativan** [tomaszzmuda/Xabe.FFmpeg#419]
When I run the application built with single file deployment and the ffmpeg executables in the same path, it throws the following exception:

```
Xabe.FFmpeg.Exceptions.FFmpegNotFoundException: Cannot find FFmpeg in PATH. This package needs installed FFmpeg. Please add it to your PATH variable or specify path to DIRECTORY with FFmpeg executables in FFmpeg.ExecutablesPath
         at Xabe.FFmpeg.FFmpeg.ValidateExecutables()
         at Xabe.FFmpeg.FFmpeg.FindAndValidateExecutables()
         at Xabe.FFmpeg.MediaInfo.Get(String filePath, CancellationToken cancellationToken)
         at Xabe.FFmpeg.FFmpeg.GetMediaInfo(String fileName, CancellationToken token)
```
according to [Single file deployment and executable](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview#api-incompatibility), **Assembly.Location** is not compatible with single-file deployment, an empty string will be returned. use **AppContext.BaseDirectory** instead.

**Comment by tomaszzmuda** [comment]
I'm going to investigate that issue.
You can set ffmpeg executables path to AppContext.BaseDirectory for now and it should work.
