### ISSUE TITLE
Sample code does not work.

### ISSUE THREAD

**Issue by HubKing** [tomaszzmuda/Xabe.FFmpeg#428]
https://ffmpeg.xabe.net/tutorial.html

```
private static async Task RunConversion(Queue filesToConvert)
{
    while(filesToConvert.TryDequeue(out FileInfo fileToConvert))
    {
        //Save file to the same location with changed extension
        string outputFileName = Path.ChangeExtension(fileToConvert.FullName, ".mp4");
        await Conversion.ToMp4(fileToConvert.FullName, outputFileName).Start();
        await Console.Out.WriteLineAsync($"Finished converion file [{fileToConvert.Name}]");
    }
}
```
![image](https://user-images.githubusercontent.com/10900489/202766120-6b66c805-5e8c-475c-9880-8d5b1a40dc3a.png)

https://ffmpeg.xabe.net/docs.html

```
string output = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".mp4");
var snippet = FFmpeg.Conversions.FromSnippet.Convert(Resources.MkvWithAudio, output);
IConversionResult result = await snippet.Start();
```

![image](https://user-images.githubusercontent.com/10900489/202766694-46b9b555-6b11-49dd-a9b5-c9557800c445.png)

**Comment by HubKing** [comment]
The first one seems to have been already reported by another user months ago.

The second one could be fixed with an "await".

    var snippet = await FFmpeg.Conversions.FromSnippet.Convert....

**Comment by javedcoding** [comment]
Okay I might have solution to your problem. Mine is used for converting video into images. The documentation is for dotnet5. so in dotnet6 use conversions method instead of conversion method.
`//Turn Video into images
            Func<string, string> outputFileNameBuilder = (number) => { return convertedVideoDir + "\\fileNameNo" + number + ".png"; };            
            IMediaInfo info = await FFmpeg.GetMediaInfo(testFilePath).ConfigureAwait(false);
            IVideoStream videoStream = info.VideoStreams.First()?.SetCodec(VideoCodec.png);
            IConversionResult conversionResult = await FFmpeg.Conversions.New().AddStream(videoStream).ExtractEveryNthFrame(2, outputFileNameBuilder).SetOutput(convertedVideoDir).Start(); 
            `

**Comment by tomaszzmuda** [comment]
@HubKing 
I've updated both examples in the documentation. If you see more issues feel free to tell me
