### ISSUE TITLE
Extract video frames to MemoryStream.

### ISSUE THREAD

**Issue by TMworldTM** [tomaszzmuda/Xabe.FFmpeg#448]
Is it possible to extract each frame from a video into a separate `MemoryStream`?

I tried to do it with `<IConversion>.PipeOutput(PipeDescriptor.stdout)` and `<IConversion>.OnVideoDataReceived` but no information is output in `OnVideoDataReceived`.

**Comment by tomaszzmuda** [comment]
Hello @TMworldTM 
It's not possible with current implementation. It can be changed and it should work but I won't have time for that in nearest future.

**Comment by TMworldTM** [comment]
Okay.
