### ISSUE TITLE
Download on Windows for ARM

### ISSUE THREAD

**Issue by nlogozzo** [tomaszzmuda/Xabe.FFmpeg#449]
Hi, I'm using this library to develop an application that also has support for Windows on ARM.  
When running the function to download FFMPEG, `Xabe.FFmpeg.Downloader.FFmpeg.Downloader.GetLatestVersion()` I get an error thrown: `Missing system type and architecture` at `Xabe.FFmpeg.Downloader.OperatingSystemProvider.GetOperatingSystem()`. Now i understand FFmpeg doesn't have ARM builds for Windows, however Windows on ARM supports running x86-64 EXEs no problem, therefore we should still download that version for now since it will work.

**Comment by tomaszzmuda** [comment]
Merged that. I will deploy new version in a couple of days
