### ISSUE TITLE
Error when converting .h264 files to .mp4

### ISSUE THREAD

**Issue by younganakin** [tomaszzmuda/Xabe.FFmpeg#45]
I am trying to convert a bunch of .h264 files to .mp4 but am getting the below error.

Exception thrown: 'System.DivideByZeroException' in Xabe.FFmpeg.dll
An exception of type 'System.DivideByZeroException' occurred in Xabe.FFmpeg.dll but was not handled in user code
Attempted to divide by zero.

The part throwing the error is below lines.

bool result = await new Conversion()
                .AddParameter("-movflags +faststart")
                .Concatenate(pathList.ToArray())
                .StreamCopy(Channel.Both)
                .SetBitstreamFilter(Channel.Audio, Filter.Aac_AdtstoAsc)
                .SetOutput(output)
                .Start();

The pathList.ToArray()) is List<string> pathList containing full paths to the .h264 files.

Any help will be greatly appreciated.

**Comment by tomaszzmuda** [comment]
I got few messages there is a problem concatenating .mp4 videos.
I'm currently changing how concatenate works, please give me few days to end and test it.

**Comment by tomaszzmuda** [comment]
I've changed concatenate method. It's in testing now. If you want you can download alpha nuget package on gitter or clone branch concat_filter.

**Comment by younganakin** [comment]
You the best @tomazzmuda😆Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [tomaszzmuda/Xabe.FFmpeg] Error when converting .h264 files to .mp4 (#45)From: Tomasz Żmuda To: "tomaszzmuda/Xabe.FFmpeg" CC: younganakin ,Author I've changed concatenate method. It's in testing now. If you want you can download alpha nuget package on gitter or clone branch concat_filter.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tomaszzmuda/Xabe.FFmpeg","title":"tomaszzmuda/Xabe.FFmpeg","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tomaszzmuda/Xabe.FFmpeg"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tomaszzmuda in #45: I've changed concatenate method. It's in testing now. If you want you can download alpha nuget package on gitter or clone branch concat_filter."}],"action":{"name":"View Issue","url":"https://github.com/tomaszzmuda/Xabe.FFmpeg/issues/45#issuecomment-350106939"}}}
