### ISSUE TITLE
Can't stop video with CancellationToken when AddDesktopStream

### ISSUE THREAD

**Issue by SidArtem** [tomaszzmuda/Xabe.FFmpeg#453]
I tried to init stream with
```
FFmpeg.Conversions.New()
            .AddDesktopStream()
            .SetOutput(output)
            .Start(cts.Token);
```
Also i have
```
var cts = new CancellationTokenSource();

_ = Task.Run(async () =>
{
    await Task.Delay(5000);
    cts.Cancel();
});
```

After that i got System.OperationCanceledException and my video is not saved in folder.

**Comment by tomaszzmuda** [comment]
Hello @SidArtem 

Have you tried to set SetInputTime on your conversion? Maybe it will be suitable for your case.

Anyway, I'm going to investigate what happened.

**Comment by tomaszzmuda** [comment]
You can look on #454 
It's not ready and not completely tested but it works in your situation.

**Comment by SidArtem** [comment]
yes, it works. thank you 🤝
waiting for the next release =)
