### ISSUE TITLE
How to generate video from pictures? 

### ISSUE THREAD

**Issue by hibobby** [tomaszzmuda/Xabe.FFmpeg#46]
Thank you for your Xabe.FFmpeg.
I not find generate video from pictures in document/Wiki .
Can you tell how to do it?

**Comment by lkischler** [comment]
Hello, there is no dedicated mehod for do that but it is possible using additional parameters. See [https://github.com/tomaszzmuda/Xabe.FFmpeg/wiki#own-arguments](doc) and for example [https://stackoverflow.com/questions/24961127/ffmpeg-create-video-from-images](FFmpeg create video from images). By this method you can use every ffmpeg features.

**Comment by tomaszzmuda** [comment]
It's like @lkischler said.
But it would be nice to add this kind of functionality to Xabe.FFmpeg.
Added to my TODO list.

**Comment by hibobby** [comment]
Sorry，I first contacted ffmpeg yesterday.
I've made a demo in CMD by @lkischler ‘s suggestion.
@tomaszzmuda 
If you have no time in the near future, I am happy to add this feature into Xabe.FFmpeg.

**Comment by tomaszzmuda** [comment]
@hibobby
If you could it would be awesome!

**Comment by hibobby** [comment]
@tomaszzmuda 
I use VS2015，How can I open this sln?

**Comment by tomaszzmuda** [comment]
Ahhh you cannot :(
According to [this ](https://github.com/dotnet/announcements/issues/24)the minimum version of VisualStudio if you want to contribute is 2017 15.3.

**Comment by tomaszzmuda** [comment]
It was merged in #187
