### ISSUE TITLE
new codec : x265 support

### ISSUE THREAD

**Issue by Nonobis** [tomaszzmuda/Xabe.FFmpeg#47]
Could you add support for encoding in x265 ?
Thx

**Comment by tomaszzmuda** [comment]
It is possible now. Look at this.
`            string outputPath = Path.ChangeExtension(Path.GetTempFileName(), Extensions.Mp4);
            bool conversionResult = await new Conversion()
                .SetInput(Resources.MkvWithAudio)
                .SetVideo("libx265")
                .SetOutput(outputPath)
                .Start();`

This will change output codec to "libx265". Just use SetVideo(codec_name) to IConversion.

**Comment by Nonobis** [comment]
Thanks ! I will test it :)
