### ISSUE TITLE
Split SetAudio and SetVideo functions

### ISSUE THREAD

**Issue by lkischler** [tomaszzmuda/Xabe.FFmpeg#54]
Now SetAudio and SetVideo method has 2 arguments - codec and bitrate.
It should be split and renamed.

**Comment by 06needhamt** [comment]
@lkischler Is this issue still relevant I can not find either `SetAudio` or `SetVideo` functions the only functions relating to bitrate I can find is my implementation of #172?

**Comment by tomaszzmuda** [comment]
@06needhamt you are right. 
I'm closing this issue. Thanks
