### ISSUE TITLE
Refactor VideoCodec, AudioCodec, Filter

### ISSUE THREAD

**Issue by tomaszzmuda** [tomaszzmuda/Xabe.FFmpeg#60]
VideoCodec, AudioCodec, Filter have to be refactored.
This should be deleted and user will pass codec manually or it should contains much more codecs with possibility to allow user specify manually codec.

**Comment by alex6dj** [comment]
FFmpeg is an awesome app, but for shure the help is sometimes like a huge black hole...
For experimented users it will be enought to specify the code manually. But for the less experienced one will be best to have a predefined list for select as needed and maintain both posibility (list and manually).
The list don´t need to have all of then, just the most used of then like: mpeg4, x264, x265, Xvid, MPEG 1-2, mp2, mp3, AAC, (...). Or at least the tested ones.

**Comment by alex6dj** [comment]
About Filter I´m not shure, because in fact it refers to Bitstream Filters (is not the same in FFmpeg). Maybe for some it can be confusing...
