### ISSUE TITLE
Eliminate naming voodoo

### ISSUE THREAD

**Issue by Vodolazz** [tomaszzmuda/Xabe.FFmpeg#7]
https://github.com/tomaszzmuda/Xabe.FFmpeg/blob/c8cc4232b5afa2860ede3be63a680d754ed73002/Xabe.FFmpeg/FFbase.cs#L57

Hi, it's me again. Suggest the following change:

.First(x => x.Name.Contains("ffprobe"))
.FullName;
.First(x => x.Name.Contains("FFmpeg"))
.FullName;

 to:
private const string _MPEG_FILE_NAME = "ffmpeg";
private const string _PROBE_FILE_NAME = "ffprobe";

.First(x => x.Name.ToLower().Contains(_PROBE_FILE_NAME))
.FullName;
.First(x => x.Name.ToLower().Contains(_MPEG_FILE_NAME))
.FullName;

Suggest this change for both calls.
I'm having both exe files in lower case and current solution gave me exception :(

btw. also it'll be good idea to wrap all this in try-catch block, because now if linq fails to find file with needed name in the user-provided dir it throws linq exception which is rather misleading in its place.

**Comment by tomaszzmuda** [comment]
Hello,
i'm glad someone use this library :)
I'm going to fix it today in 2.0.2 hotfix.

Thank you for report bugs.
If you have more suggestions or something tell me, please.

**Comment by tomaszzmuda** [comment]
I have done it.
Now name of executables are case insensitive and you can override default names in static fields in FFbase.
I've added more clear message if FFmpeg executables wasn't found.
