### ISSUE TITLE
Error while install in nuget

### ISSUE THREAD

**Issue by OM-3kChcBjgFR2COfP** [tomaszzmuda/Xabe.FFmpeg#75]
![image](https://user-images.githubusercontent.com/20497956/34317362-f1dc8d7e-e7bd-11e7-9245-dedf22d05d7e.png)

**Comment by tomaszzmuda** [comment]
Hello.
Unfortunetly I cannot help you. 
Please use english. 
But if you tried to use Xabe.FFmpeg in. NET 4.5 it won't work. Minimum .NET version is 4.6.1.
