### ISSUE TITLE
Video Player from byte live feed

### ISSUE THREAD

**Issue by xjpmauricio** [tomaszzmuda/Xabe.FFmpeg#79]
I have an Android device that's casting the screen using a tcp connection. I can see the screen cast on a windows machine by using ffplay.exe and using the following command:
ffplay -framerate 60 -i tcp://192.168.1.66:49152?listen

Is it possible to create a Video player with your component by reading this live stream?

**Comment by tomaszzmuda** [comment]
Hello.
Sorry for huge delay.
Unfortunately it isn't possible.
You can use this library to capture screen to file and open it later.
I don't know if writing to file and playing it in the same time is possible.
