### ISSUE TITLE
One or more projects are incompatible with .NETCoreApp,Version=v2.0.

### ISSUE THREAD

**Issue by MeaningOfLights** [tomaszzmuda/Xabe.FFmpeg#8]
Hi  (its Jeremy Thompson, we spoke on Stackoverflow)

When  I open the solution in VS2017 15.2 Ent Edition, I get these 2 compilation errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		One or more projects are incompatible with .NETCoreApp,Version=v2.0.				

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project Xabe.FFmpeg is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Project Xabe.FFmpeg supports: netstandard2.0 (.NETStandard,Version=v2.0)				

I have .Net 4.7 installed. 

Googling the error indicates VS2017 is the problem: https://social.msdn.microsoft.com/Forums/vstudio/en-US/f3832fbf-d708-4440-9dee-3df6ed02622c/one-or-more-packages-are-incompatible-with-netcoreappversionv10?forum=netfxsetup

Could you let us know how to get the solution compiling? Thanks in advance.

**Comment by tomaszzmuda** [comment]
@MeaningOfLights could you tell me if you have .NET Core installed and if, in which version?

**Comment by tomaszzmuda** [comment]
With Dotnet Core SDK 2.0 everything looks fine but after i uninstalled it some problems appeared.
One of dependencies cause crashes when trying to be restored at .NET Framework project.
After deleted this dependency it is now possible to restore packages.
I hope it will works on your case too.
Please try to install version 2.0.3 of Xabe.FFmpeg
